from __future__ import annotations

from collections import defaultdict

GROUP_ORDER = [
    '未授权访问',
    '水平越权：读取',
    '水平越权：修改',
    '垂直越权：页面访问',
    '垂直越权：敏感操作',
    '可枚举令牌',
    '批量操作越权',
    '字段污染 / Mass Assignment',
    '调试接口暴露',
]

LABS = [
    {
        'domain': 'authz',
        'slug': 'unauth-report',
        'title': 'L00 未授权访问：公开敏感报表',
        'subtitle': '不是所有授权问题都发生在“已登录用户”之间，有些页面甚至完全没做登录校验。',
        'difficulty': '基础',
        'story': '教务纪律报表页原本以为“知道链接的人很少”，结果后端完全没有登录检查。',
        'endpoint': '/labs/authz/unauth-report',
        'primary_class': '未授权访问',
        'secondary_class': '无登录校验 / 直接暴露敏感页面',
        'timing_class': '立即触发',
        'defense_focus': '先做认证，再做授权',
        'teacher_path': '把“未授权”与“越权”区分开：前者连登录门槛都没有，后者是登录后权限边界错误。',
        'hints': [
            '先确认访问敏感页面前是否要求登录。',
            '如果连登录状态都不检查，就不是对象级越权，而是未授权暴露。',
            '安全模式至少要先验证会话，再谈角色或对象归属。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'authz',
        'slug': 'horizontal-orders',
        'title': 'L01 水平越权：订单详情读取',
        'subtitle': '同角色用户之间不应互相读取彼此的敏感对象。',
        'difficulty': '基础',
        'story': '学员纪念品订单页只要求登录，却没有校验对象归属。',
        'endpoint': '/labs/authz/horizontal-orders',
        'primary_class': '水平越权：读取',
        'secondary_class': 'IDOR / 对象归属缺失',
        'timing_class': '立即触发',
        'defense_focus': '对象级授权校验',
        'teacher_path': '这是讲 IDOR 最直观的一关：同一角色，换个 id 就能看别人的东西。',
        'hints': [
            '先确认系统是否只做“已登录”检查，而没做“对象属于谁”的检查。',
            '如果参数只决定取哪条记录，却不绑定当前用户，就容易发生水平越权。',
            '安全模式必须把对象 owner 和当前用户一起校验。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz-orders 恢复订单数据。',
    },
    {
        'domain': 'authz',
        'slug': 'horizontal-notes',
        'title': 'L02 水平越权：他人便签修改',
        'subtitle': '能读别人的数据是一类问题，能改别人的数据则更严重。',
        'difficulty': '进阶',
        'story': '课后总结便签只按 note_id 更新，没有绑定 owner。',
        'endpoint': '/labs/authz/horizontal-notes',
        'primary_class': '水平越权：修改',
        'secondary_class': '对象更新缺少 owner 校验',
        'timing_class': '立即触发',
        'defense_focus': '写操作同样做对象级授权',
        'teacher_path': '用它讲“授权不仅影响读，也影响写”。',
        'hints': [
            '看更新接口是根据 note_id 直接修改，还是同时校验当前用户。',
            '只要能定位到别人的对象，又没有 owner 检查，就可能发生横向篡改。',
            '安全模式要让 UPDATE / DELETE 也绑定 owner 条件。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz-notes 恢复便签。',
    },
    {
        'domain': 'authz',
        'slug': 'vertical-admin-report',
        'title': 'L03 垂直越权：管理报表访问',
        'subtitle': '前端隐藏入口不等于真正鉴权。',
        'difficulty': '基础',
        'story': '管理报表页在菜单里只给管理员显示，但路由本身没有做角色校验。',
        'endpoint': '/labs/authz/vertical-admin-report',
        'primary_class': '垂直越权：页面访问',
        'secondary_class': '仅前端隐藏 / 后端未校验',
        'timing_class': '立即触发',
        'defense_focus': '后端强制角色校验',
        'teacher_path': '专门用来打掉“把按钮藏起来就算权限控制”的误区。',
        'hints': [
            '不要只看菜单是否隐藏，要看实际路由是否做后端鉴权。',
            '如果用户能直接访问敏感页面地址，前端隐藏入口没有意义。',
            '安全模式必须在服务器端检查角色。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'authz',
        'slug': 'vertical-ticket-close',
        'title': 'L04 垂直越权：敏感工单操作',
        'subtitle': '高权限动作不应只靠“按钮是否展示”控制。',
        'difficulty': '进阶',
        'story': '关闭工单的 POST 接口默认相信前端只有管理员会点到它。',
        'endpoint': '/labs/authz/vertical-ticket-close',
        'primary_class': '垂直越权：敏感操作',
        'secondary_class': '动作级授权缺失',
        'timing_class': '立即触发',
        'defense_focus': '动作级后端鉴权 / 审计',
        'teacher_path': '这关适合讲页面访问与敏感动作是两层不同的授权点。',
        'hints': [
            '看 POST 操作接口是否在服务器端再次校验角色。',
            '只要操作接口本身不做限制，隐藏按钮并不能阻止直接提交请求。',
            '安全模式应让动作级别的每个接口都执行角色检查。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz-tickets 恢复工单状态。',
    },
    {
        'domain': 'authz',
        'slug': 'enumerable-token',
        'title': 'L05 可枚举发票 token',
        'subtitle': '用顺序 token 当"权限"，等于把对象级授权写在客户端。',
        'difficulty': '进阶',
        'story': '财务系统让发票 PDF 仅凭 access_token 即可下载，但 token 是 tok-2024-NNNN。',
        'endpoint': '/labs/authz/enumerable-token',
        'primary_class': '可枚举令牌',
        'secondary_class': '"知道链接的人很少" 反模式',
        'timing_class': '立即触发',
        'defense_focus': '令牌随机化 + 服务端绑定 owner 校验',
        'teacher_path': '与 unauth-report 形成对照：一个完全没鉴权，一个用伪鉴权。',
        'hints': [
            '看 token 的格式是不是顺序的、可猜测的。',
            '即使加上 token，也必须再在服务端校验当前用户与 owner。',
            '安全模式：token 用 secrets.token_urlsafe + owner 校验。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz-invoices 恢复发票数据。',
    },
    {
        'domain': 'authz',
        'slug': 'mass-assignment',
        'title': 'L06 Mass Assignment 改 owner',
        'subtitle': '更新接口接受任意字段，攻击者顺手把 owner_user_id 改给自己。',
        'difficulty': '高级',
        'story': '便签编辑接口直接把表单字段拼进 UPDATE，没有字段白名单。',
        'endpoint': '/labs/authz/mass-assignment',
        'primary_class': '字段污染 / Mass Assignment',
        'secondary_class': '字段白名单缺失',
        'timing_class': '立即触发',
        'defense_focus': '字段白名单 + DTO 模型',
        'teacher_path': '强调"接受任意字段 = 字段级越权"。',
        'hints': [
            '在表单里多加一个 owner_user_id 字段试试。',
            '安全模式：UPDATE 仅允许 body 字段。',
            '生产中常见原因：用 ORM 的 fill(request.form) 这类便利写法。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz-notes 恢复便签。',
    },
    {
        'domain': 'authz',
        'slug': 'role-via-pref',
        'title': 'L07 偏好接口里偷偷改 role',
        'subtitle': '一个看似无害的"用户偏好" PUT，把 role 字段也吞了进去。',
        'difficulty': '高级',
        'story': '账户偏好接口允许 PUT 一段 JSON，开发把整段 JSON merge 进 user 表。',
        'endpoint': '/labs/authz/role-via-pref',
        'primary_class': '字段污染 / Mass Assignment',
        'secondary_class': 'JSON merge / role 提升',
        'timing_class': '立即触发',
        'defense_focus': '字段白名单 + role 字段独立审批流',
        'teacher_path': '让学生看到"普通业务接口也能成为权限提升通道"。',
        'hints': [
            '在 PUT JSON 里加 "role":"admin"，看是否生效。',
            '安全模式：偏好接口只接 theme/language/newsletter 三个字段。',
            'role 这种敏感字段必须走单独的审批接口。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz 重置用户与偏好。',
    },
    {
        'domain': 'authz',
        'slug': 'bulk-delete',
        'title': 'L08 批量删除越权',
        'subtitle': '逐条接口校验了 owner，批量接口却接受任意 ids 数组。',
        'difficulty': '进阶',
        'story': '"清空便签"按钮调用批量删除接口，循环执行 DELETE WHERE id IN (?)。',
        'endpoint': '/labs/authz/bulk-delete',
        'primary_class': '批量操作越权',
        'secondary_class': '批量接口与单条接口校验不一致',
        'timing_class': '立即触发',
        'defense_focus': '批量接口同样要 WHERE owner = current_user',
        'teacher_path': '提醒"补一处单条接口的鉴权" ≠ 整个对象都安全。',
        'hints': [
            '观察单条 vs. 批量接口的鉴权差异。',
            '在批量接口里塞别人的 note_id 试试。',
            '安全模式：批量删除也要 WHERE owner_user_id = ?。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz-notes 恢复便签。',
    },
    {
        'domain': 'authz',
        'slug': 'message-receiver',
        'title': 'L09 私信接收人未校验',
        'subtitle': '只查 message_id 不查 receiver，等于任何登录用户能读所有私信。',
        'difficulty': '基础',
        'story': '私信预览接口只用 message_id 查表，没绑定 receiver_user_id。',
        'endpoint': '/labs/authz/message-receiver',
        'primary_class': '水平越权：读取',
        'secondary_class': '私信 / 关系型对象',
        'timing_class': '立即触发',
        'defense_focus': 'WHERE message_id = ? AND receiver_user_id = ?',
        'teacher_path': '把 IDOR 推到关系型对象上：私信不仅 owner，还有 receiver。',
        'hints': [
            '换一个不属于自己的 message_id 试试。',
            '安全模式：必须同时校验 receiver。',
            '提示：admin 通常允许越级，但要明文写在条件里。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh authz-messages 恢复私信。',
    },
    {
        'domain': 'authz',
        'slug': 'jwt-none-alg',
        'title': 'L10 JWT alg=none 伪造',
        'subtitle': 'JWT 的 alg 头部如果没强制校验，攻击者可把 alg 改成 none 自签身份。',
        'difficulty': '高级',
        'story': '后端用 JWT 校验"x-fieldlab-token" 头，但 vuln 模式接受 alg=none。',
        'endpoint': '/labs/authz/jwt-none-alg',
        'primary_class': '垂直越权：敏感操作',
        'secondary_class': 'JWT 算法混淆 / alg=none',
        'timing_class': '立即触发',
        'defense_focus': '强制 alg 白名单（HS256/RS256）+ 拒绝 none',
        'teacher_path': '把课程从对象级授权扩展到"凭证伪造"。',
        'hints': [
            '观察 vuln 模式怎么解析 token 头部 alg。',
            '构造 alg=none 的 token，把 payload 改成 role=admin。',
            '安全模式：alg 必须 in {HS256}，且签名校验通过。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'authz',
        'slug': 'debug-endpoint',
        'title': 'L11 调试接口未鉴权',
        'subtitle': '上线前忘删的 /debug/_internal 把整张表 dump 出去了。',
        'difficulty': '基础',
        'story': '排障期间加了 /labs/authz/debug-endpoint?table=auth_users，上线后没删。',
        'endpoint': '/labs/authz/debug-endpoint',
        'primary_class': '调试接口暴露',
        'secondary_class': '调试 / 内部接口暴露',
        'timing_class': '立即触发',
        'defense_focus': '调试接口仅在开发环境启用 + 强制鉴权',
        'teacher_path': '回收"上线前清单"的话题：调试接口与日志接口同样危险。',
        'hints': [
            '试试 ?table=auth_users 或 ?table=auth_invoices。',
            '安全模式：拒绝任何未携带 X-Debug-Token 的访问。',
            '生产建议：debug 路由用 feature flag 屏蔽。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
]

LAB_INDEX = {item['slug']: item for item in LABS}

def get_lab(slug: str):
    return LAB_INDEX[slug]

def build_taxonomy():
    grouped = defaultdict(list)
    for item in LABS:
        grouped[item['primary_class']].append(item)
    return [{'name': name, 'labs': grouped[name]} for name in GROUP_ORDER if grouped[name]]
