from __future__ import annotations

from collections import defaultdict

GROUP_ORDER = [
    '无 Token 状态修改',
    '伪防护：Referer / Header 检查',
    'JSON API / Content-Type CSRF',
    '退出登录 / 偏好修改',
    'Cookie 属性缺失',
    'GET 触发副作用',
    'Double Submit 错误实现',
    'CORS / 跨源请求误用',
    '点击劫持协同 CSRF',
]

LABS = [
    {
        'domain': 'csrf',
        'slug': 'transfer-no-token',
        'title': 'L01 无 Token 转账',
        'subtitle': '最经典的 CSRF：已登录用户的状态修改请求没有任何一次性防护。',
        'difficulty': '基础',
        'story': '课堂钱包支持表单转账，但表单没有 CSRF token。',
        'endpoint': '/labs/csrf/transfer-no-token',
        'primary_class': '无 Token 状态修改',
        'secondary_class': '表单 POST 无一次性令牌',
        'timing_class': '受害者访问恶意页面时触发',
        'defense_focus': 'CSRF Token / SameSite / 二次确认',
        'teacher_path': '第一关先讲清 CSRF 的核心：浏览器会自动带上受害者自己的身份。',
        'hints': [
            '先确认状态修改请求是否需要任何随机 token。',
            '如果浏览器会自动携带 session，而请求本身又没有额外校验，就满足了 CSRF 条件。',
            '安全模式至少需要一次性 token。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf 重置钱包与日志。',
    },
    {
        'domain': 'csrf',
        'slug': 'referer-check',
        'title': 'L02 伪防护：只查 Referer',
        'subtitle': 'Referer 检查可以辅助，但把它当唯一防线通常不够。',
        'difficulty': '进阶',
        'story': '安全同学要求加来源校验，开发只写了一个脆弱的字符串包含判断。',
        'endpoint': '/labs/csrf/referer-check',
        'primary_class': '伪防护：Referer / Header 检查',
        'secondary_class': '字符串 contains 校验',
        'timing_class': '跨站自动提交时触发',
        'defense_focus': '严格 Origin/Referer + Token，不依赖字符串包含',
        'teacher_path': '这关适合讲“辅助信号”和“核心防护”不是一回事。',
        'hints': [
            '先看服务端如何判断请求来源。',
            '如果只是 contains 某个域名，很可能既不严格也不稳定。',
            '安全模式应把来源校验当辅助，再叠加 token。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf 重置钱包与日志。',
    },
    {
        'domain': 'csrf',
        'slug': 'json-settings',
        'title': 'L03 JSON API 偏好修改',
        'subtitle': '改成 JSON body 不会自动消除 CSRF 风险。',
        'difficulty': '进阶',
        'story': '账户偏好接口升级成 JSON API，但仍使用 Cookie 会话。',
        'endpoint': '/labs/csrf/json-settings',
        'primary_class': 'JSON API / Content-Type CSRF',
        'secondary_class': 'Cookie 会话 + 缺少 CSRF token',
        'timing_class': '跨站脚本或表单封装时触发',
        'defense_focus': 'Token / SameSite / 严格 Content-Type 与认证方案分离',
        'teacher_path': '重点打破“JSON 就天然防 CSRF”的误区。',
        'hints': [
            '看接口认证是不是仍然依赖浏览器自动附带的 Cookie。',
            '如果答案是是，那就还存在被第三方页面借用身份的空间。',
            '安全模式应把 token 验证和 Cookie 会话一起考虑。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf-wallets 重置账户偏好。',
    },
    {
        'domain': 'csrf',
        'slug': 'logout-and-mfa',
        'title': 'L04 登出 / MFA 偏好 CSRF',
        'subtitle': 'CSRF 不只会转账，也会破坏安全配置和会话状态。',
        'difficulty': '基础',
        'story': '账户中心允许一键关闭 MFA 或登出全部设备，但没有 token 校验。',
        'endpoint': '/labs/csrf/logout-and-mfa',
        'primary_class': '退出登录 / 偏好修改',
        'secondary_class': '安全配置变更无 CSRF 防护',
        'timing_class': '受害者打开恶意页面时触发',
        'defense_focus': '敏感操作重新认证 / Token / 双击确认',
        'teacher_path': '这关提醒学生：CSRF 影响的是“以受害者身份发出的状态修改”，不止财务动作。',
        'hints': [
            '看关闭 MFA、退出登录这样的动作是否也只是普通 POST。',
            '只要浏览器能自动带身份，安全配置同样可能被跨站页面改掉。',
            '安全模式对敏感安全动作应更严格。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf-wallets 重置账户偏好。',
    },
    {
        'domain': 'csrf',
        'slug': 'samesite-missing',
        'title': 'L05 SameSite 缺失：跨站自动带 Cookie',
        'subtitle': 'SameSite=None 等于明确允许跨站携带身份 Cookie。',
        'difficulty': '基础',
        'story': '某老旧业务为兼容三方嵌入，把 SameSite 设成 None 但没加 Secure，浏览器允许跨站请求自动带身份。',
        'endpoint': '/labs/csrf/samesite-missing',
        'primary_class': 'Cookie 属性缺失',
        'secondary_class': 'SameSite=None / Lax / Strict',
        'timing_class': '受害者访问恶意页面时触发',
        'defense_focus': 'SameSite=Lax 默认 + 敏感动作 Strict + Secure',
        'teacher_path': '让学生看到 SameSite 属性的不同值如何左右"自动带 Cookie"。',
        'hints': [
            '观察响应里 Set-Cookie 的 SameSite 取值。',
            '把它设成 None 后，跨站 fetch / form 提交都会带 Cookie。',
            '安全模式：SameSite=Lax + Secure 即可堵住绝大多数 CSRF。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'csrf',
        'slug': 'get-side-effect',
        'title': 'L06 GET 触发副作用',
        'subtitle': '把状态修改写在 GET 上，浏览器加载图片就能完成攻击。',
        'difficulty': '基础',
        'story': '"快捷转账"接口为了"链接分享方便"用了 GET 方法。',
        'endpoint': '/labs/csrf/get-side-effect',
        'primary_class': 'GET 触发副作用',
        'secondary_class': '幂等性 / HTTP 方法语义',
        'timing_class': '受害者加载恶意 img 即可触发',
        'defense_focus': '副作用必须用 POST/PUT/DELETE + Token',
        'teacher_path': '回收 RFC 关于"GET 应当安全幂等"的规定。',
        'hints': [
            '试 <img src="/labs/csrf/get-side-effect?to_user=mallory&amount=10">。',
            '安全模式：拒绝 GET，只允许 POST + token。',
            '提示：GET 加 token 也不够，因为 referer 会泄漏。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf-wallets 重置账户偏好。',
    },
    {
        'domain': 'csrf',
        'slug': 'double-submit-broken',
        'title': 'L07 Double Submit Cookie 错误实现',
        'subtitle': 'Token 同时放在 Cookie 和表单——但攻击者能控制 Cookie 值，等于自欺欺人。',
        'difficulty': '高级',
        'story': '开发听说 "Double Submit Cookie" 模式后实现了一版，但 token 来源仍可被攻击者污染。',
        'endpoint': '/labs/csrf/double-submit-broken',
        'primary_class': 'Double Submit 错误实现',
        'secondary_class': 'Cookie 注入 / 子域信任',
        'timing_class': '受害者访问攻击页时触发',
        'defense_focus': 'Double Submit 必须配合 HttpOnly + 服务端绑定会话',
        'teacher_path': '告诉学生：双提交模式只有"Cookie 不可被攻击者控制"才有效。',
        'hints': [
            '观察 token 是怎么对比的：Cookie==Form？',
            '想想攻击者能不能通过子域写 Cookie 来污染主域的 token。',
            '安全模式：服务端把 token 与会话绑定，不再做"Cookie==Form"的纸面比较。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf-wallets 重置账户偏好。',
    },
    {
        'domain': 'csrf',
        'slug': 'cors-credentials',
        'title': 'L08 CORS 配置失误：credentials + 任意 Origin',
        'subtitle': 'Access-Control-Allow-Origin 镜像 Origin + Allow-Credentials=true，相当于给跨站发了 VIP 卡。',
        'difficulty': '高级',
        'story': '为方便调试，开发把 Allow-Origin 直接镜像成请求 Origin，并允许携带 Cookie。',
        'endpoint': '/labs/csrf/cors-credentials',
        'primary_class': 'CORS / 跨源请求误用',
        'secondary_class': '反射 Origin + Allow-Credentials',
        'timing_class': '跨站 fetch 时触发',
        'defense_focus': 'Allow-Origin 用白名单；带 credentials 不能配 *',
        'teacher_path': '让学生意识到 CORS "宽松配置 + Cookie" 等于 CSRF + 数据外带。',
        'hints': [
            '观察响应头是否把 Origin 完整反射进 Access-Control-Allow-Origin。',
            '安全模式：只允许同源；Allow-Credentials 仅对白名单 Origin 开启。',
            'Cookie + 任意 Origin = 跨站自由读写，属于授权层面的灾难。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf-wallets 重置账户偏好。',
    },
    {
        'domain': 'csrf',
        'slug': 'clickjacking-mfa',
        'title': 'L09 点击劫持协同 CSRF：关闭 MFA',
        'subtitle': '没有 X-Frame-Options 时，把目标页用透明 iframe 套住即可诱骗点击。',
        'difficulty': '高级',
        'story': '"关闭 MFA"按钮没加 frame ancestors 限制，攻击者可以用透明 iframe 套住它。',
        'endpoint': '/labs/csrf/clickjacking-mfa',
        'primary_class': '点击劫持协同 CSRF',
        'secondary_class': 'X-Frame-Options / frame-ancestors',
        'timing_class': '受害者点击伪装按钮时触发',
        'defense_focus': 'X-Frame-Options: DENY 或 CSP frame-ancestors',
        'teacher_path': '把 CSRF 和点击劫持放一起讲：很多防御层面是同一类问题。',
        'hints': [
            '查看响应是否带 X-Frame-Options 或 CSP frame-ancestors。',
            '本课在 vuln 模式不带，safe 模式补上。',
            '提示：纯 SameSite 无法挡住"用户自己点了按钮"。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf-wallets 重置账户偏好。',
    },
    {
        'domain': 'csrf',
        'slug': 'host-header-token',
        'title': 'L10 Host header 影响 token 计算',
        'subtitle': 'token 用 Host 拼算，攻击者改 Host 即可让目标自己生成"对得上的" token。',
        'difficulty': '高级',
        'story': '某个"无状态" CSRF 方案：token = HMAC(secret, host + path)。',
        'endpoint': '/labs/csrf/host-header-token',
        'primary_class': 'Double Submit 错误实现',
        'secondary_class': 'Host header injection / 无状态 token',
        'timing_class': '攻击者构造特殊 Host 头时触发',
        'defense_focus': 'token 与会话绑定 + 强制 Host 白名单',
        'teacher_path': '强调"无状态 token"如果输入受外部影响就不再可信。',
        'hints': [
            '本课会反射当前 Host 用于计算 token。',
            '伪造 Host 头让 token 与你"对得上"，即可绕过校验。',
            '安全模式：token 改用 session id + 服务端 secret 计算，不依赖 Host。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh csrf-wallets 重置账户偏好。',
    },
]

LAB_INDEX = {item['slug']: item for item in LABS}

def get_lab(slug: str):
    return LAB_INDEX[slug]

def build_taxonomy():
    grouped = defaultdict(list)
    for item in LABS:
        grouped[item['primary_class']].append(item)
    return [{'name': name, 'labs': grouped[name]} for name in GROUP_ORDER if grouped[name]]
