from __future__ import annotations

from collections import defaultdict

GROUP_ORDER = [
    '代码注入',
    '命令注入',
    '模板注入（与 SSTI 对照）',
    '反序列化',
    '环境变量 / 子进程',
    '第三方命令拼接',
]

LABS = [
    {
        'domain': 'injection',
        'slug': 'python-eval',
        'title': 'L01 Python eval 代码注入',
        'subtitle': '把用户表达式直接交给 eval，本质上就是把解释器暴露给了输入。',
        'difficulty': '基础',
        'story': '价格试算台允许老师输入“公式”，服务端直接 eval。',
        'endpoint': '/labs/injection/python-eval',
        'primary_class': '代码注入',
        'secondary_class': 'eval / 表达式执行',
        'timing_class': '立即触发',
        'defense_focus': 'AST 白名单 / 禁止解释执行不可信表达式',
        'teacher_path': '用最直观的 eval 把“代码注入”概念立住，再讲安全替代。',
        'hints': [
            '先观察输入是不是被当成代码求值，而不是普通字符串。',
            '只要用户能影响解释器执行内容，风险就已经成立。',
            '安全模式通常用 AST 白名单或显式映射，不继续让表达式自由执行。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'injection',
        'slug': 'stored-exec',
        'title': 'L02 存储后 exec 规则执行',
        'subtitle': '用户提交的脚本先存下来，真正的执行发生在后续规则预演。',
        'difficulty': '高级',
        'story': '自动化规则编辑器允许老师写 Python 片段，预演时用 exec 跑起来。',
        'endpoint': '/labs/injection/stored-exec',
        'primary_class': '代码注入',
        'secondary_class': 'exec / 存储后二次执行',
        'timing_class': '存储后触发',
        'defense_focus': '禁用脚本能力 / DSL 白名单',
        'teacher_path': '这关把代码注入也讲成生命周期问题：保存和执行是两步。',
        'hints': [
            '先确认规则会不会被保存，再看预演是不是把它当脚本执行。',
            '数据库里的脚本内容并不会因为“已经保存”就变安全。',
            '安全模式应把规则改成固定 DSL 或受限字段。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh injection-snippets 重置规则。',
    },
    {
        'domain': 'injection',
        'slug': 'command-diagnose',
        'title': 'L03 诊断命令拼接',
        'subtitle': 'shell=True + 字符串拼接，是命令注入最常见的课堂入口。',
        'difficulty': '基础',
        'story': '运维诊断面板会把目标主机拼进 shell 命令里。',
        'endpoint': '/labs/injection/command-diagnose',
        'primary_class': '命令注入',
        'secondary_class': 'shell=True / 参数拼接',
        'timing_class': '立即触发',
        'defense_focus': '参数列表调用 / 禁用 shell',
        'teacher_path': '这关适合讲“命令解释器也是解释器”，和代码注入一脉相承。',
        'hints': [
            '看服务端是不是把整条命令拼成一个字符串后交给 shell。',
            '只要 shell 会重新解析用户内容，输入就可能变成新的命令片段。',
            '安全模式要用参数数组，避免 shell 参与二次解析。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'injection',
        'slug': 'command-grep',
        'title': 'L04 grep 日志检索命令注入',
        'subtitle': '不是只有系统命令诊断台，日常运维工具同样可能把用户词条拼进 shell。',
        'difficulty': '进阶',
        'story': '日志检索器为了省事直接拼出 `grep -n <keyword> file`。',
        'endpoint': '/labs/injection/command-grep',
        'primary_class': '命令注入',
        'secondary_class': 'grep / 查询参数拼接',
        'timing_class': '立即触发',
        'defense_focus': '参数数组 / 固定子命令 / 转义不是根治',
        'teacher_path': '这关能让学生看到：即使只是“搜索关键词”，也可能进入命令解释链。',
        'hints': [
            '关注 keyword 最终是不是成为 shell 命令的一部分。',
            '如果命令字符串里直接拼 keyword，grep 只是外壳，真正危险的是 shell。',
            '安全模式要把 keyword 当普通参数传入，不拼整个命令串。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh injection 重置规则与日志。',
    },
    {
        'domain': 'injection',
        'slug': 'jinja-render-string',
        'title': 'L05 render_template_string 拼接',
        'subtitle': '"诊断接口" 用 render_template_string 直接吃用户输入 → SSTI',
        'difficulty': '高级',
        'story': '一个内部诊断面板用 render_template_string 把 user_input 当模板渲染。',
        'endpoint': '/labs/injection/jinja-render-string',
        'primary_class': '模板注入（与 SSTI 对照）',
        'secondary_class': 'render_template_string / Jinja2',
        'timing_class': '立即触发',
        'defense_focus': '禁止把外部输入当模板源；用 render_template + 变量传参',
        'teacher_path': '与 SSTI 域 L01 形成对照：同样的危险动作出现在"非业务模板"的诊断接口里。',
        'hints': [
            '试 {{ 7*7 }}，看是否被求值。',
            '试 {{ config }} 或 {{ self.__class__ }} 探查。',
            '安全模式：用 render_template + context dict，绝不让用户控制模板源。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'injection',
        'slug': 'yaml-load',
        'title': 'L06 YAML 不安全加载',
        'subtitle': 'yaml.load() 默认会执行 !!python/object/apply 等构造器。',
        'difficulty': '高级',
        'story': '配置导入接口接受 YAML，使用 yaml.load(stream, Loader=yaml.Loader)。',
        'endpoint': '/labs/injection/yaml-load',
        'primary_class': '反序列化',
        'secondary_class': 'YAML / pickle 反序列化',
        'timing_class': '解析时立即触发',
        'defense_focus': 'yaml.safe_load + 拒绝任意 Python 构造器',
        'teacher_path': '把"反序列化 = 任意代码执行"的核心讲清楚。',
        'hints': [
            'PoC：!!python/object/apply:os.system ["id > /tmp/pwned"]',
            '观察 vuln 是否真的执行了 system 调用。',
            '安全模式：yaml.safe_load 拒绝所有 Python 构造器。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'injection',
        'slug': 'env-injection',
        'title': 'L07 环境变量值进入 shell',
        'subtitle': 'env=dict + shell=True 时，dict value 会被 shell 二次解析。',
        'difficulty': '进阶',
        'story': '部署诊断脚本把用户 target 写入 LC_FIELDLAB_TARGET，再用 shell 命令读它。',
        'endpoint': '/labs/injection/env-injection',
        'primary_class': '环境变量 / 子进程',
        'secondary_class': '环境变量 + shell=True',
        'timing_class': '立即触发',
        'defense_focus': '不与 shell 拼接 + env 不接外部输入',
        'teacher_path': '提醒"env 不是天然安全的，shell 仍会展开变量"。',
        'hints': [
            '试 target=`id` 或 target=$(id)，观察 vuln 是否解析。',
            '安全模式：用 ["printenv","LC_FIELDLAB_TARGET"] 不走 shell。',
            '提示：很多容器排障脚本都吃过这个亏。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'injection',
        'slug': 'shlex-shell-true',
        'title': 'L08 shlex.split 后还 shell=True',
        'subtitle': '"我已经 shlex.split 了"——但你又把它 join 回字符串，仍然交给 shell。',
        'difficulty': '高级',
        'story': '开发听说 shlex.split 能防注入，但写法是 subprocess.run(" ".join(shlex.split(cmd)), shell=True)。',
        'endpoint': '/labs/injection/shlex-shell-true',
        'primary_class': '命令注入',
        'secondary_class': 'shlex 误用 / 假防御',
        'timing_class': '立即触发',
        'defense_focus': 'shell=False + 直接传 list；不要重新 join',
        'teacher_path': '强调"防御要看最终送进 shell 的字符串，而不是中间 token 化过"。',
        'hints': [
            '试 keyword=foo;id，观察 vuln 是否 join 回去后被 shell 解析。',
            '安全模式：shell=False 直接传 ["echo", keyword]。',
            '生产建议：把命令构造器封装成只接受 list 的 helper。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'injection',
        'slug': 'grep-extended-pattern',
        'title': 'L09 grep -E 正则可控',
        'subtitle': '正则模式可控本身已经是 ReDoS 面，再叠 shell=True 直接 RCE。',
        'difficulty': '进阶',
        'story': '高级日志检索允许用户给"正则"，后端用 grep -E + shell=True。',
        'endpoint': '/labs/injection/grep-extended-pattern',
        'primary_class': '命令注入',
        'secondary_class': 'shell=True + 正则模式可控',
        'timing_class': '立即触发',
        'defense_focus': '参数列表 + 正则在应用层用 re.compile + 超时',
        'teacher_path': '把命令注入与 ReDoS 双面风险一起讲。',
        'hints': [
            '试 pattern="x;id #"，观察 vuln 是否被 shell 解释。',
            '试 pattern="(a+)+$" + 长输入，观察 ReDoS。',
            '安全模式：用 Python re.compile + re.findall，不走 grep / shell。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh injection 重置日志。',
    },
    {
        'domain': 'injection',
        'slug': 'git-ref-injection',
        'title': 'L10 git ref 拼接命令注入',
        'subtitle': '`git log <ref>` 看似只接 ref，但拼字符串后 ref 可注入新参数 / 新命令。',
        'difficulty': '高级',
        'story': '部署诊断面板调用 git log <ref>，ref 来自请求参数，shell=True 拼接。',
        'endpoint': '/labs/injection/git-ref-injection',
        'primary_class': '第三方命令拼接',
        'secondary_class': '运维脚本拼接外部 CLI',
        'timing_class': '立即触发',
        'defense_focus': '参数数组 + 严格 ref 字符集校验',
        'teacher_path': '提醒"调用任何外部 CLI 都必须用参数数组 + 限制字符集"。',
        'hints': [
            '试 ref="HEAD;id"，观察 vuln 是否执行 id。',
            '试 ref="--help"，观察是否能切换到任意 git 子命令选项。',
            '安全模式：ref 必须匹配 ^[A-Za-z0-9._/-]{1,64}$，且用 list 调用。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
]

LAB_INDEX = {item['slug']: item for item in LABS}

def get_lab(slug: str):
    return LAB_INDEX[slug]

def build_taxonomy():
    grouped = defaultdict(list)
    for item in LABS:
        grouped[item['primary_class']].append(item)
    return [{'name': name, 'labs': grouped[name]} for name in GROUP_ORDER if grouped[name]]
