from __future__ import annotations

from collections import defaultdict

GROUP_ORDER = [
    '客户端价格 / 数量信任',
    '优惠券与折扣逻辑',
    '回调与对账逻辑',
    '浮点 / 单位精度',
    '退款 / 状态机',
    '签名与重放',
    '并发库存',
]

LABS = [
    {
        'domain': 'payment',
        'slug': 'client-total',
        'title': 'L01 客户端总价篡改',
        'subtitle': '服务端如果直接相信前端提交的 total，价格就等于交给用户自己填。',
        'difficulty': '基础',
        'story': '订单确认页为了适配前端活动价，直接接收客户端 total 字段。',
        'endpoint': '/labs/payment/client-total',
        'primary_class': '客户端价格 / 数量信任',
        'secondary_class': '客户端 total 字段',
        'timing_class': '提交订单时触发',
        'defense_focus': '服务端重算金额',
        'teacher_path': '第一关先讲“支付逻辑漏洞不一定需要注入，信任边界错了就够了”。',
        'hints': [
            '先区分谁在算价格：浏览器还是服务端。',
            '如果 total 直接来自客户端，价格边界就已经失守。',
            '安全模式应完全忽略客户端 total，按服务端商品单价重算。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment-orders 重置支付订单。',
    },
    {
        'domain': 'payment',
        'slug': 'negative-quantity',
        'title': 'L02 负数数量与余额反向增加',
        'subtitle': '数量和金额的符号校验缺失，可能把扣款逻辑变成充值逻辑。',
        'difficulty': '进阶',
        'story': '点券购买器允许输入数量，后端直接做 balance -= quantity * price。',
        'endpoint': '/labs/payment/negative-quantity',
        'primary_class': '客户端价格 / 数量信任',
        'secondary_class': '负数 / 符号校验缺失',
        'timing_class': '提交购买时触发',
        'defense_focus': '数量范围校验 / 服务端业务规则',
        'teacher_path': '这关适合引出“支付逻辑漏洞的核心常常是状态机和约束失效”。',
        'hints': [
            '看数量字段是否限制为正整数。',
            '如果扣款公式没有先验证语义，负数可能让结果反向。',
            '安全模式要先验证数量，再做余额变更。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment-wallet 重置钱包余额。',
    },
    {
        'domain': 'payment',
        'slug': 'coupon-reuse',
        'title': 'L03 优惠券重复使用',
        'subtitle': '优惠券验证通过后如果不正确消耗，就会被无限复用。',
        'difficulty': '进阶',
        'story': '一次性优惠券在 UI 上会变灰，但服务端没有真正扣减使用次数。',
        'endpoint': '/labs/payment/coupon-reuse',
        'primary_class': '优惠券与折扣逻辑',
        'secondary_class': '一次性券未正确消耗',
        'timing_class': '提交订单时触发',
        'defense_focus': '服务端扣减 / 原子更新 / 幂等消费',
        'teacher_path': '这关适合讲“客户端表现”和“服务端真实状态”是两件事。',
        'hints': [
            '先看优惠券是否真的在服务端减少次数。',
            '如果只是校验“还有效”，却不消耗状态，就能重复用。',
            '安全模式必须在同一事务里完成校验和扣减。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment-coupons 重置优惠券。',
    },
    {
        'domain': 'payment',
        'slug': 'duplicate-callback',
        'title': 'L04 重复支付回调',
        'subtitle': '回调不是只会来一次，不做幂等就会重复记账。',
        'difficulty': '高级',
        'story': '支付网关回调处理器每收到一次 success 都给用户加一次点券。',
        'endpoint': '/labs/payment/duplicate-callback',
        'primary_class': '回调与对账逻辑',
        'secondary_class': '缺少幂等处理',
        'timing_class': '回调到达时触发',
        'defense_focus': '订单状态机 / 回调幂等键',
        'teacher_path': '用它讲清“支付逻辑的安全边界不只在下单，还在异步通知和对账”。',
        'hints': [
            '先确认订单是否记录“已经处理过回调”。',
            '如果每个 success 都直接记账，就会被重复利用。',
            '安全模式要基于订单状态或回调幂等键去重。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment 重置支付状态。',
    },
    {
        'domain': 'payment',
        'slug': 'float-precision',
        'title': 'L05 浮点累加精度漏洞',
        'subtitle': '`0.1 + 0.2 != 0.3`：用 float 算金额，可被构造序列累出"少一分钱"。',
        'difficulty': '进阶',
        'story': '充值结算用 float 累加，攻击者构造 1000 笔 0.1 元充值后实际余额比预期少。',
        'endpoint': '/labs/payment/float-precision',
        'primary_class': '浮点 / 单位精度',
        'secondary_class': 'IEEE-754 累加误差',
        'timing_class': '提交多笔金额时累计触发',
        'defense_focus': 'Decimal 或整数分计算',
        'teacher_path': '让学生看到"金额必须用 Decimal 或最小货币单位整数"。',
        'hints': [
            '试连续提交 1000 笔 0.1 元，观察 expected vs. actual。',
            '安全模式用 decimal.Decimal 精确累加。',
            '生产建议：金额一律存 cents（int64）。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment-wallet 重置钱包余额。',
    },
    {
        'domain': 'payment',
        'slug': 'currency-unit',
        'title': 'L06 货币单位混淆（分 / 元）',
        'subtitle': '前端按"分"提交，后端按"元"入账，1 元商品收成 100 元。',
        'difficulty': '基础',
        'story': '前后端缺乏单位约定：前端 amount=100 表示 1 元，后端按 100 元创建订单。',
        'endpoint': '/labs/payment/currency-unit',
        'primary_class': '浮点 / 单位精度',
        'secondary_class': '前后端单位约定缺失',
        'timing_class': '下单时触发',
        'defense_focus': '统一服务端用分；接口字段命名带单位（amount_cents）',
        'teacher_path': '提醒"接口字段命名 + 类型约束"是反 unit 漏洞的核心。',
        'hints': [
            '试 amount=1（按分=¥0.01）下单 ¥100 商品，观察是否被误解成 ¥1。',
            '安全模式：服务端只接受 amount_cents（int），并校验 == price_cents。',
            '提示：很多公司支付故障复盘第一条就是"单位不一致"。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment-orders 重置支付订单。',
    },
    {
        'domain': 'payment',
        'slug': 'refund-overpay',
        'title': 'L07 退款金额可控',
        'subtitle': '退款接口让客户端指定 refund_amount，未校验是否超过订单 paid_amount。',
        'difficulty': '进阶',
        'story': '退款接口接受客户端 refund_amount 字段，没和 paid_amount 比对。',
        'endpoint': '/labs/payment/refund-overpay',
        'primary_class': '退款 / 状态机',
        'secondary_class': '退款金额未校验上限',
        'timing_class': '提交退款时触发',
        'defense_focus': '退款金额必须 <= 已支付金额 - 已退金额',
        'teacher_path': '把"退款"作为独立的金额边界来讲。',
        'hints': [
            '试 refund_amount > paid_amount 看 vuln 是否照单全退。',
            '安全模式：refund_amount 必须 <= paid_amount - sum(已退)。',
            '生产中常见：退款接口忘了 join 已退记录。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment 重置支付状态。',
    },
    {
        'domain': 'payment',
        'slug': 'state-machine',
        'title': 'L08 订单状态机错位',
        'subtitle': '没有显式状态机：refunded 之后再调用 capture 又能把状态设回 paid。',
        'difficulty': '高级',
        'story': '订单 status 字段允许任意覆盖，refunded -> paid -> refunded 可循环。',
        'endpoint': '/labs/payment/state-machine',
        'primary_class': '退款 / 状态机',
        'secondary_class': '状态转换未约束',
        'timing_class': '调用任意状态变更接口时触发',
        'defense_focus': '显式状态机表（FROM, TO 白名单）',
        'teacher_path': '把退款问题升级为"状态机设计"问题。',
        'hints': [
            '依次调用 pay -> refund -> pay -> refund，观察 vuln 是否允许。',
            '安全模式：拒绝 refunded -> paid 的状态转换。',
            '生产建议：状态机配 enum + 转换矩阵。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment-orders 重置订单。',
    },
    {
        'domain': 'payment',
        'slug': 'signature-replay',
        'title': 'L09 回调签名重放',
        'subtitle': '签名只覆盖 order_ref + amount，没有 nonce / timestamp，可任意重放。',
        'difficulty': '高级',
        'story': '支付网关回调签名 = HMAC(secret, order_ref + amount)，没有时间戳。',
        'endpoint': '/labs/payment/signature-replay',
        'primary_class': '签名与重放',
        'secondary_class': '缺少 nonce / timestamp',
        'timing_class': '重复提交回调时触发',
        'defense_focus': '签名覆盖 nonce + timestamp + 服务端去重',
        'teacher_path': '把签名讲成"完整性 + 抗重放"两件事，缺一不可。',
        'hints': [
            '本课提供"生成合法签名" + "重放" 两个按钮，观察 vuln 多次记账。',
            '安全模式：签名必须含 nonce，服务端记录已用 nonce。',
            '常见误区：以为有 HTTPS 就不会重放。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment 重置支付状态。',
    },
    {
        'domain': 'payment',
        'slug': 'oversell-flash',
        'title': 'L10 限量秒杀超卖（支付侧）',
        'subtitle': '"先查库存再扣"在并发下会超卖；安全模式用条件 UPDATE 原子扣减。',
        'difficulty': '高级',
        'story': '"5 张限量代金券" 用先 SELECT 后 UPDATE 的写法，并发下能领出多张。',
        'endpoint': '/labs/payment/oversell-flash',
        'primary_class': '并发库存',
        'secondary_class': 'SELECT-then-UPDATE / TOCTOU',
        'timing_class': '高并发请求时触发',
        'defense_focus': 'UPDATE ... WHERE remaining > 0 + 检查 rowcount',
        'teacher_path': '与 race 域形成对照：race 强调多接口竞争，本课强调单接口并发。',
        'hints': [
            '页面提供"并发抢 20 次"按钮，比对 vuln 与 safe 的最终领取数。',
            '安全模式：UPDATE coupons SET remaining = remaining - 1 WHERE code = ? AND remaining > 0，看 rowcount。',
            '提示：SQLite 写锁在测试时也能复现，但生产用 MySQL 行锁更典型。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh payment-coupons 重置代金券。',
    },
]

LAB_INDEX = {item['slug']: item for item in LABS}

def get_lab(slug: str):
    return LAB_INDEX[slug]

def build_taxonomy():
    grouped = defaultdict(list)
    for item in LABS:
        grouped[item['primary_class']].append(item)
    return [{'name': name, 'labs': grouped[name]} for name in GROUP_ORDER if grouped[name]]
