from __future__ import annotations

from collections import defaultdict

GROUP_ORDER = [
    '任意目标抓取',
    '字符串白名单绕过',
    '重定向链 SSRF',
    '盲 SSRF / 副作用观测',
    'IP / DNS 解析差异',
    '云元数据 / 内部 API',
    '协议滥用',
    '响应反射 / 数据外带',
]

LABS = [
    {
        'domain': 'ssrf',
        'slug': 'basic-fetch',
        'title': 'L01 任意目标抓取',
        'subtitle': '服务端替用户发请求，本质上就是把网络信任边界交出去了。',
        'difficulty': '基础',
        'story': '链接预览组件会在服务端抓取目标页面摘要。',
        'endpoint': '/labs/ssrf/basic-fetch',
        'primary_class': '任意目标抓取',
        'secondary_class': '服务端回显型 SSRF',
        'timing_class': '立即触发',
        'defense_focus': '协议 / 主机 / 网段限制',
        'teacher_path': '先讲“不是浏览器请求，而是服务端请求”，再引导学生打内部地址。',
        'hints': [
            '确认请求到底从谁发出：浏览器还是服务端。',
            '如果服务端能访问浏览器访问不到的主机，价值就会立刻提升。',
            '安全模式至少要限制协议和私有网段。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'allowlist-bypass',
        'title': 'L02 字符串白名单绕过',
        'subtitle': '只看 URL 前缀的“白名单”很容易被解析差异绕过。',
        'difficulty': '进阶',
        'story': '预览服务只允许抓取 `preview-gateway`，但校验只用了 startswith。',
        'endpoint': '/labs/ssrf/allowlist-bypass',
        'primary_class': '字符串白名单绕过',
        'secondary_class': 'userinfo / 解析差异',
        'timing_class': '立即触发',
        'defense_focus': '解析后再校验 hostname',
        'teacher_path': '适合讲 URL 的“看起来像什么”和“真正会连到哪里”是两回事。',
        'hints': [
            '先区分字符串检查和真正的 URL 解析结果。',
            '如果过滤器只做 startswith，可能根本没看实际 hostname。',
            '安全模式必须在 parse 之后看 scheme/hostname/port。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'redirect-follow',
        'title': 'L03 重定向链 SSRF',
        'subtitle': '即使第一跳看起来安全，自动跟随重定向也可能把请求带进内网。',
        'difficulty': '进阶',
        'story': '预览器要求首个域名必须是 `preview-gateway`，但默认会跟随 302。',
        'endpoint': '/labs/ssrf/redirect-follow',
        'primary_class': '重定向链 SSRF',
        'secondary_class': '首跳安全 / 终跳危险',
        'timing_class': '立即触发',
        'defense_focus': '禁用自动重定向或逐跳重验',
        'teacher_path': '强调“不是校验一次就结束”，后续跳转同样要视作新请求。',
        'hints': [
            '先看抓取器是否自动跟随 3xx。',
            '如果只校验第一跳地址，重定向链就可能变成新的入口。',
            '安全模式可以禁用重定向，或对每一跳都做相同校验。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'blind-log',
        'title': 'L04 盲 SSRF 与副作用日志',
        'subtitle': '页面不回显响应体，也可能通过耗时、状态码和服务器日志观察副作用。',
        'difficulty': '高级',
        'story': '后台探测器只告诉用户“抓取任务已完成”，实际结果写入服务端日志。',
        'endpoint': '/labs/ssrf/blind-log',
        'primary_class': '盲 SSRF / 副作用观测',
        'secondary_class': '状态码 / 耗时 / 服务器日志',
        'timing_class': '立即触发',
        'defense_focus': '限制出站能力 / 缩小访问面 / 审计日志',
        'teacher_path': '把 SSRF 从“读响应体”扩展到“观察副作用”，更接近真实业务。',
        'hints': [
            '如果页面不直接回显，也要看有没有时间差、状态差或日志差。',
            '内部服务的可达性未必通过正文体现，也可能通过副作用被证明。',
            '安全模式重点是减少服务端能触达的范围。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh ssrf 清空 SSRF 日志。',
    },
    {
        'domain': 'ssrf',
        'slug': 'ip-encoding',
        'title': 'L05 IP 编码绕过（十进制 / 十六进制 / 八进制）',
        'subtitle': '只看字符串里"是不是 127.0.0.1"，会被各种合法的 IP 表示法绕过。',
        'difficulty': '进阶',
        'story': '抓取器禁用了 127.0.0.1 字面，但忘了同一 IP 还有十进制（2130706433）、十六进制（0x7f000001）等写法。',
        'endpoint': '/labs/ssrf/ip-encoding',
        'primary_class': 'IP / DNS 解析差异',
        'secondary_class': 'IP 多种合法表示',
        'timing_class': '立即触发',
        'defense_focus': '解析后做 ipaddress 对象判定，而非字符串匹配',
        'teacher_path': '把"协议解析差异"扩展到 IP 表示差异。',
        'hints': [
            '试试 http://2130706433/ 或 http://0x7f000001/ 是否能到达本地。',
            '安全模式：不再做字符串黑名单，改用 ipaddress.ip_address 判 is_loopback。',
            '提示：DNS 解析后再判可以一并堵住绑了内网 IP 的域名。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'cloud-metadata',
        'title': 'L06 云厂商元数据接口',
        'subtitle': 'IMDSv1 风格元数据接口让 SSRF 变成"一键拿凭证"。',
        'difficulty': '高级',
        'story': '链接预览器允许访问任意 http URL，攻击者直接读取云元数据接口拿临时 IAM 凭证。',
        'endpoint': '/labs/ssrf/cloud-metadata',
        'primary_class': '云元数据 / 内部 API',
        'secondary_class': 'IMDS / 链路本地地址',
        'timing_class': '立即触发',
        'defense_focus': '禁止访问 169.254.169.254 / IMDSv2 + 强制 token',
        'teacher_path': '把 SSRF 与云原生场景结合：典型的"读响应=拿密钥"。',
        'hints': [
            '本课用 intranet 的 /latest/meta-data/* 路径模拟 IMDS。',
            '攻击：http://intranet:7001/latest/meta-data/iam/security-credentials/lab-role',
            '安全模式：解析 hostname 后拒绝 169.254.0.0/16 整段。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'header-injection',
        'title': 'L07 请求头注入抵达 admin API',
        'subtitle': '抓取器允许业务自定义请求头，攻击者顺势伪造内部认证头。',
        'difficulty': '高级',
        'story': '产品经理希望抓取时能带上自定义 header，开发把 form 字段直接转成请求头。',
        'endpoint': '/labs/ssrf/header-injection',
        'primary_class': '云元数据 / 内部 API',
        'secondary_class': '可控请求头 / 内部认证头',
        'timing_class': '立即触发',
        'defense_focus': '禁止用户自定义敏感前缀头（X-Internal- / Authorization）',
        'teacher_path': '强调"SSRF + 头部可控 = 内部认证一并被冒充"。',
        'hints': [
            '本课内部 API 凭 X-Internal-Token: lab-internal-token 即可访问。',
            '攻击：在自定义 headers 中添加 X-Internal-Token: lab-internal-token，URL 指向 /internal/secret-export。',
            '安全模式：自定义头白名单，禁掉 X-Internal- / Authorization。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'file-protocol',
        'title': 'L08 file:// 协议读本地文件',
        'subtitle': 'urllib 默认就支持 file://，URL 校验只挡 http(s) 名单是不够的。',
        'difficulty': '基础',
        'story': '某个旧版抓取脚本只校验"必须以 http 开头"，但底层用了 urllib。',
        'endpoint': '/labs/ssrf/file-protocol',
        'primary_class': '协议滥用',
        'secondary_class': 'file:// / ftp:// / gopher://',
        'timing_class': '立即触发',
        'defense_focus': '协议白名单只放行 http/https',
        'teacher_path': '用最直白的 file:// 让学生体会"协议本身是攻击面"。',
        'hints': [
            '尝试 file:///etc/hostname 或 file:///app/config.py。',
            '安全模式：parse 后强制 scheme in {http,https}。',
            '提示：file:// 不会跨网；但仍能读容器本地任意文件。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'crlf-smuggling',
        'title': 'L09 URL 内 CRLF 走私',
        'subtitle': 'URL 中的 %0d%0a 在某些客户端会被注入到原始请求里。',
        'difficulty': '高级',
        'story': '抓取器把 path 直接拼进 raw HTTP 请求；CRLF 让攻击者注入额外 header。',
        'endpoint': '/labs/ssrf/crlf-smuggling',
        'primary_class': '协议滥用',
        'secondary_class': 'HTTP 请求拼接 / CRLF 注入',
        'timing_class': '立即触发',
        'defense_focus': '使用成熟 HTTP 客户端 + 校验 path 不含 CR/LF',
        'teacher_path': '让学生看到"自己手写 HTTP 请求"的隐藏代价。',
        'hints': [
            '本课 vuln 模式用裸 socket 拼请求，path 中允许 \\r\\n。',
            '攻击：path=/internal/echo-headers HTTP/1.1\\r\\nX-Internal-Token: lab-internal-token\\r\\n…',
            '安全模式：拒绝 path 含任何控制字符。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'dns-rebinding',
        'title': 'L10 DNS 重绑定（教学等价演示）',
        'subtitle': '校验时解析为公网 IP，真正请求时解析为内网 IP——两次解析差异。',
        'difficulty': '高级',
        'story': '抓取器先 socket.gethostbyname 校验 hostname，再单独发起请求。',
        'endpoint': '/labs/ssrf/dns-rebinding',
        'primary_class': 'IP / DNS 解析差异',
        'secondary_class': 'TOCTOU / 双次解析',
        'timing_class': '立即触发',
        'defense_focus': '解析一次拿到 IP 后用 IP 直接发请求；或同步绑定校验',
        'teacher_path': '展示 TOCTOU 的"DNS 解析"版本，引出"统一一次解析"思路。',
        'hints': [
            '本课用 hostname=rebind.lab 模拟：第一次 resolver 返回公网 IP，第二次返回 intranet。',
            '安全模式：第一次解析后直接拿 ip 串发请求，不再重新查 DNS。',
            '生产环境推荐绑定 IP 池而不是 hostname。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'response-reflection',
        'title': 'L11 响应反射型数据外带',
        'subtitle': '即使没有"读响应体"按钮，回显字段也能成为外带通道。',
        'difficulty': '进阶',
        'story': '抓取页只回显 status code 和 final_url，但 final_url 把跳转目标的 path 完整反射。',
        'endpoint': '/labs/ssrf/response-reflection',
        'primary_class': '响应反射 / 数据外带',
        'secondary_class': 'final_url / status / 错误信息回显',
        'timing_class': '立即触发',
        'defense_focus': '不要回显完整 final_url；只显示 hostname',
        'teacher_path': '让学生意识到"看似只回显元数据"也可能是外带通道。',
        'hints': [
            '让 intranet 把目标内容编码进 redirect 的 path，再观察 final_url。',
            '安全模式：仅回显 hostname / 状态码，不回显 path。',
            '提示：错误信息中的 reason 也常常带数据。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssrf',
        'slug': 'time-based-blind',
        'title': 'L12 基于时间差的盲 SSRF',
        'subtitle': '没有响应、没有日志，时间差仍然能告诉你内网谁在线。',
        'difficulty': '高级',
        'story': '抓取器对外完全不回显，但响应耗时随目标可达性变化。',
        'endpoint': '/labs/ssrf/time-based-blind',
        'primary_class': '盲 SSRF / 副作用观测',
        'secondary_class': '耗时 timing oracle',
        'timing_class': '立即触发',
        'defense_focus': '统一超时 / 抹平 timing；限制出站',
        'teacher_path': '把盲 SSRF 推到极致：连日志都没有，仍能推断网络拓扑。',
        'hints': [
            '本课会返回固定文案，但内部抓取的耗时随目标变化。',
            '对比 http://intranet:7001/slow?seconds=1 与 ?seconds=4 的耗时。',
            '安全模式：服务端补足固定耗时（time-based padding）。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh ssrf 清空 SSRF 日志。',
    },
]

LAB_INDEX = {item['slug']: item for item in LABS}

def get_lab(slug: str):
    return LAB_INDEX[slug]

def build_taxonomy():
    grouped = defaultdict(list)
    for item in LABS:
        grouped[item['primary_class']].append(item)
    return [{'name': name, 'labs': grouped[name]} for name in GROUP_ORDER if grouped[name]]
