from __future__ import annotations

from collections import defaultdict

GROUP_ORDER = [
    '直接模板渲染',
    '表达式包装',
    '存储后二次渲染',
    '受信片段拼接',
    '沙箱逃逸',
    '其他模板引擎',
    '客户端模板',
    '模板内文件/命令',
    '配置驱动模板',
]

LABS = [
    {
        'domain': 'ssti',
        'slug': 'reflected-template',
        'title': 'L01 直接 render_template_string',
        'subtitle': '把用户输入直接当成模板源码渲染，是最直观的 SSTI 起点。',
        'difficulty': '基础',
        'story': '欢迎卡片预览器允许老师自定义模板片段。',
        'endpoint': '/labs/ssti/reflected-template',
        'primary_class': '直接模板渲染',
        'secondary_class': 'Jinja 表达式执行',
        'timing_class': '立即触发',
        'defense_focus': '不要把不可信字符串送进模板引擎',
        'teacher_path': '先让学生理解“模板语法就是代码”，再讲为什么普通 HTML 转义根本不够。',
        'hints': [
            '观察输入是不是被当作模板源码，而不是普通变量值。',
            '如果输入里的模板语法被解析，说明执行边界已经在服务端丢失。',
            '安全模式应该把模板当数据展示，而不是继续交给引擎。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'expression-wrapper',
        'title': 'L02 表达式包装型 SSTI',
        'subtitle': '用户只提交表达式，服务端却主动替它补上模板定界符。',
        'difficulty': '进阶',
        'story': '报表配置器只让老师输入“表达式主体”，后端自动补成完整模板。',
        'endpoint': '/labs/ssti/expression-wrapper',
        'primary_class': '表达式包装',
        'secondary_class': '服务端主动拼模板',
        'timing_class': '立即触发',
        'defense_focus': '不要拼接模板语法；对可计算表达式做白名单',
        'teacher_path': '这关适合讲“用户没写 {{ }} 不代表后端没帮他补上”。',
        'hints': [
            '看输入是不是被包进了某个固定模板结构。',
            '一旦后端把表达式包进 {{ ... }}，用户控制的就不再只是普通文本。',
            '安全模式通常需要改成显式字段映射，而不是继续让表达式可执行。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'stored-mail',
        'title': 'L03 存储后二次渲染邮件模板',
        'subtitle': '第一次只是保存模板，真正的执行发生在后续预览环节。',
        'difficulty': '高级',
        'story': '教务邮件模板保存在数据库里，预览页每次都会重新渲染。',
        'endpoint': '/labs/ssti/stored-mail',
        'primary_class': '存储后二次渲染',
        'secondary_class': '模板持久化传播',
        'timing_class': '存储后触发',
        'defense_focus': '存储后再次输出时仍不能信任模板内容',
        'teacher_path': '把 SSTI 也讲成“第一次存储、第二次触发”的生命周期问题。',
        'hints': [
            '先确认模板会不会被保存，再确认预览时是否重新喂给引擎。',
            '如果数据库里的内容被当作模板源码，第一次保存再安全也没意义。',
            '修复时不要只在保存入口做过滤。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh ssti-mail 恢复默认邮件模板。',
    },
    {
        'domain': 'ssti',
        'slug': 'theme-fragment',
        'title': 'L04 受信片段拼接',
        'subtitle': '开发以为“只是主题片段”，却把不可信片段拼进完整模板。',
        'difficulty': '高级',
        'story': '主题编辑器允许自定义横幅片段，并和系统模板合并渲染。',
        'endpoint': '/labs/ssti/theme-fragment',
        'primary_class': '受信片段拼接',
        'secondary_class': '大模板内嵌小模板',
        'timing_class': '立即触发',
        'defense_focus': '主题片段做白名单或完全取消模板能力',
        'teacher_path': '这关适合讲“受信模板 + 不可信局部片段”也是危险组合。',
        'hints': [
            '观察系统是不是先拿用户片段拼出一个更大的模板，再一起渲染。',
            '局部可控不代表风险小，只要最后进入引擎就是同等危险。',
            '安全模式通常会改成预定义组件或纯文本占位。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh ssti-theme 恢复默认主题片段。',
    },
    {
        'domain': 'ssti',
        'slug': 'sandbox-escape',
        'title': 'L05 Jinja 沙箱逃逸（mro 链）',
        'subtitle': '看似只放行了字符串的过滤器，仍能通过对象 mro 链摸到危险类。',
        'difficulty': '高级',
        'story': '运维认为只要禁掉 import / eval 关键字就能让 Jinja 变沙箱。',
        'endpoint': '/labs/ssti/sandbox-escape',
        'primary_class': '沙箱逃逸',
        'secondary_class': 'object.__mro__ / __subclasses__',
        'timing_class': '立即触发',
        'defense_focus': '使用 SandboxedEnvironment + 不让用户控制模板源码',
        'teacher_path': '展示『关键字黑名单 ≠ 真沙箱』；引出 SandboxedEnvironment 与最小化 globals。',
        'hints': [
            '试试 {{ ().__class__.__mro__ }} 看类层次。',
            '再用 __subclasses__() 找 file/Popen 之类的类。',
            '安全模式应彻底拒绝模板源码，不再依赖关键字过滤。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'tornado-dialect',
        'title': 'L06 不同模板引擎方言（Tornado 风格）',
        'subtitle': '换个模板引擎，定界符也变了；常规 Jinja 黑名单立刻失效。',
        'difficulty': '进阶',
        'story': '历史邮件系统用 Tornado 模板：定界符是 {% raw %}{% ... %}{% endraw %} 和 {% raw %}{{ ... }}{% endraw %}，但表达式语义和 Jinja 不同。',
        'endpoint': '/labs/ssti/tornado-dialect',
        'primary_class': '其他模板引擎',
        'secondary_class': 'Tornado / Mako / Velocity 方言',
        'timing_class': '立即触发',
        'defense_focus': '识别真正在用的模板引擎；不要只靠 Jinja 经验做防御',
        'teacher_path': '强调防御要看运行时引擎，而不是想当然以为是 Jinja。',
        'hints': [
            '方言不同，{{ 7*7 }} 在不同引擎里输出不一样。',
            '看 vuln 模式如何用 Python 内置 string.Template 模拟另一种方言。',
            '关键不是会不会执行，而是『定界符 + 表达式语义』被攻击者控制。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'client-angular',
        'title': 'L07 客户端模板（AngularJS 风格）',
        'subtitle': '前端模板 {{ }} 也是代码，绕过 Jinja 不代表绕不过浏览器引擎。',
        'difficulty': '进阶',
        'story': '老报表页用一个 mini AngularJS 风格的前端模板引擎渲染 banner。',
        'endpoint': '/labs/ssti/client-angular',
        'primary_class': '客户端模板',
        'secondary_class': '浏览器内 expression 引擎',
        'timing_class': '立即触发',
        'defense_focus': '前端引擎也要把不可信片段当数据，不要塞进表达式',
        'teacher_path': '把 SSTI 推广到客户端：模板 = 代码，与运行环境无关。',
        'hints': [
            '在 vuln 模式输入 {{ 7*7 }} 看是否被前端 eval 算出 49。',
            '试试 {{ constructor.constructor("return 1+2")() }} 这类逃逸思路。',
            '安全模式应只取字符串、不进入表达式求值。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'file-read',
        'title': 'L08 SSTI 读本地文件',
        'subtitle': '能渲染模板就能读文件——这是模板引擎天然的能力。',
        'difficulty': '高级',
        'story': '运维让模板引擎能读 /tmp/lab/ssti_secret.txt 作为水印。',
        'endpoint': '/labs/ssti/file-read',
        'primary_class': '模板内文件/命令',
        'secondary_class': 'open() / get_template / include',
        'timing_class': '立即触发',
        'defense_focus': '禁止模板内 IO；走显式 include 白名单',
        'teacher_path': '把 SSTI 危险性具象化：不是抽象 RCE，而是直接读文件。',
        'hints': [
            'Jinja config / get_template 的对象都可被 mro 链摸到。',
            '试试 {{ ().__class__.__mro__[1].__subclasses__() }} 找到含 open 的类。',
            '安全模式应明确禁止任意文件路径读取。',
        ],
        'reset': '无需重置；secret 文件由 Docker entrypoint 写入。',
    },
    {
        'domain': 'ssti',
        'slug': 'command-exec',
        'title': 'L09 SSTI 执行系统命令',
        'subtitle': 'mro 摸到 Popen 后，模板引擎就成了 RCE 入口。',
        'difficulty': '高级',
        'story': '运维做了一个『模板里也能跑 git 命令』的『便利功能』。',
        'endpoint': '/labs/ssti/command-exec',
        'primary_class': '模板内文件/命令',
        'secondary_class': 'subprocess.Popen / os.system',
        'timing_class': '立即触发',
        'defense_focus': '禁止模板内进程调用；最小化 Jinja globals',
        'teacher_path': '把 SSTI 与命令注入合流，强调最小权限原则。',
        'hints': [
            'vuln 模式给模板上下文里加了 cmd = subprocess 对象。',
            '攻击：{{ cmd.check_output(["id"]).decode() }}',
            '安全模式：context 只放纯数据。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'double-render',
        'title': 'L10 二次渲染：title 与 body 都进引擎',
        'subtitle': '存储模板的 title 字段也被渲染——多入口意味着多攻击面。',
        'difficulty': '高级',
        'story': '运维补丁只过滤了 body 字段，但 title 字段也参与了模板拼装。',
        'endpoint': '/labs/ssti/double-render',
        'primary_class': '存储后二次渲染',
        'secondary_class': '多字段同时进入引擎',
        'timing_class': '存储后触发',
        'defense_focus': '所有进引擎的字段都要审计，不要只防一个',
        'teacher_path': '说明『漏掉一个字段 = 完全没有防御』。',
        'hints': [
            '观察 title 是否也在最终模板里被解析。',
            '试试在 title 里写 {{ 7*7 }} 看是否被算出。',
            '安全模式：title 用 escape，body 当数据。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'json-key',
        'title': 'L11 配置 JSON 的 key 也进了模板',
        'subtitle': 'key 经常被开发者忽略，但拼进模板时一样危险。',
        'difficulty': '进阶',
        'story': '配置中心允许上传 JSON，渲染时把 key 当 label、value 当内容。',
        'endpoint': '/labs/ssti/json-key',
        'primary_class': '配置驱动模板',
        'secondary_class': 'JSON key → 模板片段',
        'timing_class': '立即触发',
        'defense_focus': 'JSON 任何字段（key/value/嵌套）进引擎都要清洗',
        'teacher_path': '强调『结构化数据』里也藏着模板源码。',
        'hints': [
            '在 JSON 里把 key 写成 {{ 7*7 }} 看输出。',
            'value 同理。',
            '安全模式只把它们当字符串显示。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
    {
        'domain': 'ssti',
        'slug': 'include-path',
        'title': 'L12 include 路径可控',
        'subtitle': '让用户控制 include 的文件名，等于把文件系统暴露给模板引擎。',
        'difficulty': '进阶',
        'story': '主题系统允许选择某个『片段名』来 include。',
        'endpoint': '/labs/ssti/include-path',
        'primary_class': '受信片段拼接',
        'secondary_class': '动态 include / extends',
        'timing_class': '立即触发',
        'defense_focus': 'include 路径走白名单；不接受用户拼接',
        'teacher_path': '强调路径可控比模板源码可控更难发现。',
        'hints': [
            'vuln 模式直接用 {% raw %}{% include user_input %}{% endraw %}。',
            '试 ../../etc/passwd 等思路（沙箱内可能受限，但能看出风险）。',
            '安全模式：白名单映射 fragment_id → 模板路径。',
        ],
        'reset': '无需重置；secret include 由 Docker entrypoint 写入。',
    },
]

LAB_INDEX = {item['slug']: item for item in LABS}

def get_lab(slug: str):
    return LAB_INDEX[slug]

def build_taxonomy():
    grouped = defaultdict(list)
    for item in LABS:
        grouped[item['primary_class']].append(item)
    return [{'name': name, 'labs': grouped[name]} for name in GROUP_ORDER if grouped[name]]
