from __future__ import annotations

from collections import defaultdict

GROUP_ORDER = [
    '公开可访问上传',
    'MIME / 扩展名信任',
    '文件名 / 路径控制',
    '扩展名解析歧义',
    '内容嗅探 / Magic Bytes',
    '压缩包路径穿越',
    'SVG / 同源 HTML 执行',
    '配置文件覆盖',
    '校验时序 / TOCTOU',
    '响应反射',
]

LABS = [
    {
        'domain': 'upload',
        'slug': 'public-html',
        'title': 'L01 公开可访问 HTML 上传',
        'subtitle': '上传后的文件能被同源直接访问，浏览器会按内容执行。',
        'difficulty': '基础',
        'story': '课堂素材区允许学员上传“预览页面”。',
        'endpoint': '/labs/upload/public-html',
        'primary_class': '公开可访问上传',
        'secondary_class': '同源 HTML / SVG 执行',
        'timing_class': '上传后访问触发',
        'defense_focus': '限制类型 + 非同源存储 / 强制下载',
        'teacher_path': '先讲“文件上传不等于代码执行”，但只要同源可访问的 HTML/SVG 就会进入浏览器执行链。',
        'hints': [
            '先看上传后的文件是不是会在同源路径下直接打开。',
            '如果浏览器把它当 HTML/SVG 解析，文件本身就成了新的页面。',
            '安全模式应阻止危险类型，或至少强制附件下载。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload-public 重置上传文件。',
    },
    {
        'domain': 'upload',
        'slug': 'mime-trust',
        'title': 'L02 只信任 Content-Type',
        'subtitle': '如果服务器把用户声明的 MIME 直接当真，返回头本身就会放大风险。',
        'difficulty': '进阶',
        'story': '素材直传接口允许客户端声明 MIME，用于后续原样回放。',
        'endpoint': '/labs/upload/mime-trust',
        'primary_class': 'MIME / 扩展名信任',
        'secondary_class': '用户可控 Content-Type',
        'timing_class': '上传后访问触发',
        'defense_focus': '服务端决定响应类型，不信任客户端 MIME',
        'teacher_path': '这关适合讲“不是只有文件内容危险，响应头也决定浏览器如何解释”。',
        'hints': [
            '看服务端返回文件时，Content-Type 是怎么来的。',
            '如果类型完全由上传者声明，浏览器就会按那个类型解释。',
            '安全模式要由服务端重新判定或降级为下载。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload-public 重置上传文件。',
    },
    {
        'domain': 'upload',
        'slug': 'filename-traversal',
        'title': 'L03 文件名路径穿越与覆盖',
        'subtitle': '文件上传不只影响“内容”，文件名本身也可能改写写入位置。',
        'difficulty': '高级',
        'story': '公告横幅会读取 data 目录中的固定文件，而上传器直接使用用户文件名拼路径。',
        'endpoint': '/labs/upload/filename-traversal',
        'primary_class': '文件名 / 路径控制',
        'secondary_class': '路径穿越 / 覆盖现有文件',
        'timing_class': '上传后立即影响',
        'defense_focus': 'basename / 随机文件名 / 固定目录',
        'teacher_path': '把“文件内容安全”扩展到“文件名安全”，帮助学生建立完整上传面思维。',
        'hints': [
            '先观察服务端如何拼接目标路径。',
            '如果文件名能包含目录分隔符，可能就不再写入预期目录。',
            '安全模式要丢弃原文件名中的路径信息，并改用随机存储名。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload 重置上传文件和横幅。',
    },
    {
        'domain': 'upload',
        'slug': 'double-extension',
        'title': 'L04 双扩展名绕过',
        'subtitle': '`.html.png` 究竟会被服务端按第一段还是最后一段识别？',
        'difficulty': '基础',
        'story': '上传过滤"取最后扩展名是否在白名单"，但实际解析靠"取第一段已知扩展名"。',
        'endpoint': '/labs/upload/double-extension',
        'primary_class': '扩展名解析歧义',
        'secondary_class': '解析与校验位置不一致',
        'timing_class': '上传后访问触发',
        'defense_focus': '只允许文件名中出现唯一扩展名 + 服务端强制响应类型',
        'teacher_path': '让学生看到"扩展名校验"和"扩展名解析"在不同模块发生时的偏差。',
        'hints': [
            '试上传 evil.html.png：服务端拿 .png 过白名单。',
            '看 vuln 模式响应是否仍按 .html 解析。',
            '安全模式：拒绝多扩展名 + 强制 Content-Type。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload-public 重置上传文件。',
    },
    {
        'domain': 'upload',
        'slug': 'extension-case',
        'title': 'L05 大小写 / 空白扩展名绕过',
        'subtitle': '`.HTML`、`evil.html.`（结尾点）、`evil.html ` 都可能被忽略后再解析。',
        'difficulty': '基础',
        'story': '校验做了 `.endswith(".html")` 但没 lower、没 strip。',
        'endpoint': '/labs/upload/extension-case',
        'primary_class': '扩展名解析歧义',
        'secondary_class': '大小写 / 末尾空白 / null 字节',
        'timing_class': '上传后访问触发',
        'defense_focus': '统一 lower + strip + 拒绝控制字符',
        'teacher_path': '强调字符串规整化必须在校验之前完成。',
        'hints': [
            '试 evil.HTML / evil.html.  / evil.html\\x00.png 三种命名。',
            '安全模式：所有命名先做 normalize 再校验。',
            '提示：Windows / macOS / Linux 对结尾点和空格的处理不同。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload-public 重置上传文件。',
    },
    {
        'domain': 'upload',
        'slug': 'magic-bytes',
        'title': 'L06 Magic Bytes 校验骗过',
        'subtitle': '只看头几个字节判定图片，恶意载荷可以拼在合法 PNG 后面。',
        'difficulty': '进阶',
        'story': '相册上传只校验前 8 字节是否为 PNG signature。',
        'endpoint': '/labs/upload/magic-bytes',
        'primary_class': '内容嗅探 / Magic Bytes',
        'secondary_class': '内容前缀检验 + 扩展名信任',
        'timing_class': '上传后访问触发',
        'defense_focus': '完整解码 + 重新编码 + 强制扩展名',
        'teacher_path': '把"魔术字节"当成必要不充分条件来讲。',
        'hints': [
            '准备一个真实 PNG，附加任意载荷在后面，命名 evil.html。',
            '观察 vuln 是否仅校验前 8 字节就放行。',
            '安全模式：用 PIL 解码并重新写出，剥离载荷。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload-public 重置上传文件。',
    },
    {
        'domain': 'upload',
        'slug': 'zip-slip',
        'title': 'L07 Zip Slip 解压路径穿越',
        'subtitle': '解压 zip 时用条目名拼路径，恶意条目名 `../../escape.txt` 可越界。',
        'difficulty': '高级',
        'story': '"批量素材包"上传后会自动解压到 uploads/zip 目录。',
        'endpoint': '/labs/upload/zip-slip',
        'primary_class': '压缩包路径穿越',
        'secondary_class': 'Zip Slip / Tar Slip',
        'timing_class': '解压时立即触发',
        'defense_focus': '解压前用 realpath 校验在目标目录下',
        'teacher_path': '提示几乎所有压缩格式都有相同模式（zip/tar/jar/7z/rar）。',
        'hints': [
            '下方提供"生成示例 zip"按钮，含 ../escape.txt 条目。',
            '观察 vuln 是否把 escape.txt 写到目标目录之外。',
            '安全模式：os.path.realpath(target).startswith(root)。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload 清理 uploads。',
    },
    {
        'domain': 'upload',
        'slug': 'svg-xss',
        'title': 'L08 SVG 内嵌脚本',
        'subtitle': 'SVG 是 XML，浏览器会执行其中的 `<script>`。',
        'difficulty': '进阶',
        'story': '头像上传允许 SVG（"为了无损"），并以同源 HTML 形式回放。',
        'endpoint': '/labs/upload/svg-xss',
        'primary_class': 'SVG / 同源 HTML 执行',
        'secondary_class': '富格式上传 + 同源回放',
        'timing_class': '上传后访问触发',
        'defense_focus': 'SVG 必须用 sanitizer 剥 script + 异源域托管',
        'teacher_path': '把 SVG 与 PDF/HTML 一起讲：富格式都是 XSS 风险源。',
        'hints': [
            '准备 svg：<svg xmlns="..."><script>fieldlab.record("svg-xss")</script></svg>',
            '观察 vuln 是否同源以 image/svg+xml 直出。',
            '安全模式：bleach.clean(svg, tags=[...], strip=True)。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload-public 重置上传文件。',
    },
    {
        'domain': 'upload',
        'slug': 'htaccess-overwrite',
        'title': 'L09 .htaccess / 配置文件覆盖',
        'subtitle': '允许上传任意文件名，攻击者覆盖目录的 .htaccess 改 MIME 映射。',
        'difficulty': '高级',
        'story': '"主题包"允许上传 .htaccess 用于自定义路由（伪场景：本课用 mime_overrides.json 模拟）。',
        'endpoint': '/labs/upload/htaccess-overwrite',
        'primary_class': '配置文件覆盖',
        'secondary_class': '.htaccess / 路由映射 / web.config',
        'timing_class': '上传后影响后续所有访问',
        'defense_focus': '黑名单文件名 + 拒绝隐藏文件 + 目录配置只读',
        'teacher_path': '强调"上传不仅写内容，也可能写配置"。',
        'hints': [
            '试上传名为 mime_overrides.json 的文件，把 .txt 映射到 text/html。',
            '观察 vuln 是否覆盖了目录配置，影响后续访问。',
            '安全模式：拒绝点开头的文件名 + 配置文件单独存放。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload 重置 mime_overrides。',
    },
    {
        'domain': 'upload',
        'slug': 'toctou-scan',
        'title': 'L10 校验前后置 / TOCTOU',
        'subtitle': '"先存到 public 再 AV 扫描"留出抢访问窗口。',
        'difficulty': '高级',
        'story': '上传后立刻把文件存进 public，几百毫秒后才校验，校验失败就删除。',
        'endpoint': '/labs/upload/toctou-scan',
        'primary_class': '校验时序 / TOCTOU',
        'secondary_class': '存储与校验顺序倒置',
        'timing_class': '上传成功到校验完成之间',
        'defense_focus': '先暂存到隔离目录，校验通过后再发布',
        'teacher_path': '把上传问题与 TOCTOU 模式联系起来。',
        'hints': [
            '观察 vuln 模式：返回 URL 是即时可访问的。',
            '点 "立即并发抢访问" 按钮可见在删除前抢到内容。',
            '安全模式：先存 quarantine，扫描通过后才挪到 public。',
        ],
        'reset': '使用 ./scripts/reset_lab.sh upload-public 清理 uploads。',
    },
    {
        'domain': 'upload',
        'slug': 'reflected-filename',
        'title': 'L11 文件名反射 XSS',
        'subtitle': '上传成功页直接把文件名拼进 HTML，文件名可控就是 XSS。',
        'difficulty': '基础',
        'story': '"上传成功"提示直接说"已收到 {filename}"，不做任何转义。',
        'endpoint': '/labs/upload/reflected-filename',
        'primary_class': '响应反射',
        'secondary_class': '文件名 -> HTML 反射',
        'timing_class': '上传后立即触发',
        'defense_focus': '所有用户输入（含 multipart 字段）都要 HTML 转义',
        'teacher_path': '提醒"上传场景"也属于 XSS 输入面。',
        'hints': [
            '把文件名命为 <img src=x onerror=fieldlab.record(\'reflected-filename\')>',
            '观察 vuln 是否直接 |safe 拼接进响应。',
            '安全模式：Jinja autoescape + 不再 |safe。',
        ],
        'reset': '无需重置；该关卡默认只读。',
    },
]

LAB_INDEX = {item['slug']: item for item in LABS}

def get_lab(slug: str):
    return LAB_INDEX[slug]

def build_taxonomy():
    grouped = defaultdict(list)
    for item in LABS:
        grouped[item['primary_class']].append(item)
    return [{'name': name, 'labs': grouped[name]} for name in GROUP_ORDER if grouped[name]]
